#!/usr/bin/env bash
# Phase 11, Stream A (X1): provisions the container-based real-hardware(-adjacent)
# idle CPU/RSS measurement. Run as root: `sudo ./setup.sh`. See ./README.md for the
# design and ../../.plan/ARCHITECTURE.md §8 for the budget this is measuring against.
#
# What this touches on the host, all reversible via ./teardown.sh:
#   - adds one `imports` line to /etc/nixos/configuration.nix (backed up first)
#   - runs `nixos-rebuild switch` (rollback: `nixos-rebuild switch --rollback`)
#   - creates /var/lib/expanse-perf/{n1,n2,n3}-persist on the host
set -euo pipefail

REPO="/home/jaredm/expanse"
MODULE="$REPO/nix/perf/containers/host-containers.nix"
CONF=/etc/nixos/configuration.nix
NAMES=(n1 n2 n3)
PERSIST_ROOT=/var/lib/expanse-perf
FORCE=${FORCE:-0}

if [[ $EUID -ne 0 ]]; then
    echo "must run as root: sudo $0" >&2
    exit 1
fi

# Full output also goes to a logfile, so a long or failed run doesn't have to be
# pasted from terminal scrollback -- `tee` keeps it live on the terminal too. Deliberately
# NOT under $PERSIST_ROOT: teardown.sh rm -rf's that, which would erase the very log it's
# writing to (and every setup.sh log before it).
LOG_DIR=/var/log/expanse-perf
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/setup-$(date +%Y%m%dT%H%M%S).log"
exec > >(tee -a "$LOG") 2>&1
echo "logging full output to $LOG"

if [[ -e /etc/nixos/.configuration.nix.swp && $FORCE -ne 1 ]]; then
    echo "refusing to proceed: /etc/nixos/.configuration.nix.swp exists (a vim session may" >&2
    echo "be mid-edit on configuration.nix). Close it, or re-run with FORCE=1 if it's stale." >&2
    exit 1
fi

echo "== 1/4: pre-creating each container's /persist (host-side) =="
for n in "${NAMES[@]}"; do
    systemctl stop "container@$n.service" 2>/dev/null || true
done
for n in "${NAMES[@]}"; do
    p="$PERSIST_ROOT/$n-persist"
    # Wiped every run so each measurement starts from a fresh node -- found live: a stale
    # cluster-id here made the next `expanse cluster init` fail "already a cluster node".
    rm -rf "$p"
    mkdir -p "$p"/{etc,var/lib/nixos,var/lib/systemd,root/.ssh}
    touch "$p/etc/machine-id"
    chmod 0700 "$p/root/.ssh"
    echo "  $p ready"
done
# /persist's bindMounts entry lives here rather than in host-containers.nix so the
# host-side path stays a setup.sh concern.
cat > /etc/nixos/expanse-perf-persist-mounts.nix <<'EOF'
# Generated by nix/perf/containers/setup.sh -- do not hand-edit; see ../../nix/perf/containers/README.md.
{ ... }: {
  containers.n1.bindMounts."/persist" = { hostPath = "/var/lib/expanse-perf/n1-persist"; isReadOnly = false; };
  containers.n2.bindMounts."/persist" = { hostPath = "/var/lib/expanse-perf/n2-persist"; isReadOnly = false; };
  containers.n3.bindMounts."/persist" = { hostPath = "/var/lib/expanse-perf/n3-persist"; isReadOnly = false; };
}
EOF

echo "== 2/4: wiring /etc/nixos/configuration.nix =="
MARK="# >>> expanse X1 perf containers (nix/perf/containers/setup.sh) >>>"
if ! grep -qF "$MARK" "$CONF"; then
    cp "$CONF" "$CONF.bak-$(date +%s)"
    python3 - "$CONF" "$MODULE" "$MARK" <<'PYEOF'
import sys
conf_path, module_path, mark = sys.argv[1:4]
text = open(conf_path).read()
insert = f"    {mark}\n    {module_path}\n    /etc/nixos/expanse-perf-persist-mounts.nix\n    # <<< expanse X1 perf containers <<<\n"
idx = text.index("imports =")
idx = text.index("[", idx) + 1
text = text[:idx] + "\n" + insert + text[idx:]
open(conf_path, "w").write(text)
PYEOF
    echo "  added import lines (backup at $CONF.bak-*)"
else
    echo "  already wired, skipping"
fi

echo "== 3/4: nixos-rebuild switch =="
# host-containers.nix's builtins.getFlake needs the flakes experimental feature.
# /etc/nix/nix.conf (system-wide, what root's nixos-rebuild actually reads) has it
# empty -- only the invoking user's own ~/.config/nix/nix.conf grants it, which root
# under sudo does not inherit. Scoped to just this command, not written to any file.
NIX_CONFIG="experimental-features = nix-command flakes" nixos-rebuild switch

echo "== 4/4: (re)starting containers so they pick up whatever was just built =="
# `restart`, not `start`: containers.<name> (autoStart = false) registers and populates
# the machine the first time container@<name>.service itself starts -- `machinectl
# start` only works on an already-registered image and fails "Machine image '<name>'
# does not exist" before that (found live). And autoStart = false ALSO disables NixOS's
# own restart-on-config-change machinery (nixos-containers.nix's restartTriggers/
# restartIfChanged are set inside `optionalAttrs containerConfig.autoStart { ... }` --
# a no-op when it's false), so `nixos-rebuild switch` alone never restarts an already-
# running container to pick up a rebuilt config -- `systemctl start` on an
# already-active unit is *also* a no-op, silently leaving the OLD process running with
# stale capabilities/devices even though the new config built and switched correctly.
# Found live: this is exactly why the CAP_MKNOD fix never took effect on a container
# that was already running successfully from the bridge fix. `restart` is correct
# whether the unit is currently stopped or running.
for n in "${NAMES[@]}"; do
    systemctl restart "container@$n.service"
done

# systemd-run --machine= depends on the container's D-Bus machine-transport socket,
# which is not reliably up yet right after start -- found live ("Failed to connect to
# system scope bus via machine transport"). nsenter into the container's own PID
# namespace via its leader PID instead (the same mechanism `nixos-container run` itself
# uses, proven to work against a running container regardless of D-Bus state).
failed=0
for n in "${NAMES[@]}"; do
    ok=0
    for i in $(seq 1 180); do
        # Re-fetch the leader PID every iteration, not just once before the loop --
        # found live: querying it immediately after `restart` can race the container's
        # own startup (leader not registered with machinectl yet), leaving it empty for
        # the whole 180s wait even though the container comes up fine seconds later.
        leader="$(machinectl show "$n" -p Leader --value 2>/dev/null)"
        # is-system-running exits non-zero for "degraded" (0 means only "running"), so
        # this must stay an if-condition rather than a bare assignment to stay exempt
        # from set -e.
        if status="$(nsenter --target "$leader" --all -- systemctl is-system-running 2>&1)"; then
            rc=0
        else
            rc=$?
        fi
        # Progress breadcrumb for a slow or stuck boot, without spamming every second.
        if (( i % 10 == 0 )); then
            echo "  $n: [$(date +%T)] leader='$leader' rc=$rc status='$status'" >&2
        fi
        if [[ -n "$leader" ]] && [[ "$status" =~ running|degraded ]]; then
            ok=1
            break
        fi
        sleep 1
    done
    if [[ $ok -eq 1 ]]; then
        echo "  $n: up ($status)"
    else
        echo "  $n: NOT ready after 180s -- last seen: leader='$leader' rc=$rc status='$status'" >&2
        failed=1
    fi
done

echo
if [[ $failed -eq 0 ]]; then
    echo "All 3 containers up. Now run the measurement (also as root):"
else
    echo "One or more containers did NOT come up cleanly -- see above before running the measurement." >&2
fi
echo "  sudo python3 $REPO/nix/perf/containers/run.py"
[[ $failed -eq 0 ]]
