# Block runtime module for security/vaultwarden.
#
# One vaultwarden per instance, active/passive over the SINGLETON strategy like
# dev/forgejo. Its SQLite database, RSA signing key and attachments live on the
# volume; expanse-block-run (vaultwarden.go) builds the environment.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     environment # the environment generated by expanse-block-run
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, environment, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (security/vaultwarden)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    inherit environment;
    serviceConfig = {
      ExecStart = "${pkgs.vaultwarden}/bin/vaultwarden";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
