# Block runtime module for dev/forgejo.
#
# One forgejo per instance, active/passive over the SINGLETON strategy like
# db/mariadb. Its repositories, SQLite database and secrets live on the
# volume; expanse-block-run (forgejo.go) writes app.ini.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     configFile  # app.ini generated by expanse-block-run
#     workPath    # Forgejo's work path on the volume
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, configFile, workPath, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (dev/forgejo)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.forgejo}/bin/forgejo web --config ${configFile} --work-path ${workPath}";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
