# Block runtime module for storage/s3.
#
# One single-node Garage per instance, active/passive over the SINGLETON
# strategy like share/nfs. Metadata, objects, the node key and the
# generated RPC secret and admin token all live on the volume, so the node
# that takes over after a failover is the same Garage node.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     configFile  # garage.toml generated by expanse-block-run (garage.go)
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, configFile, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (storage/s3)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.garage}/bin/garage -c ${configFile} server";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
