# Block runtime module for web/caddy.
#
# One caddy per instance, active/passive over the SINGLETON strategy like
# storage/s3. Its data directory (certificates, ACME account, internal CA)
# lives on the volume; expanse-block-run (caddy.go) writes the Caddyfile.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     configFile  # Caddyfile generated by expanse-block-run
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, configFile, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (web/caddy)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.caddy}/bin/caddy run --adapter caddyfile --config ${configFile}";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
