# Block runtime module for monitor/prometheus.
#
# Run singleton with a storage volume for the TSDB. The bridge hands the
# workload every voter (--scrape-node id=host) and the cluster CA bundle
# (--scrape-ca); the shipped alert rules are embedded in expanse-block-run.
#
# Contract: import and call with:
#   {
#     pkgs           # nixpkgs
#     name           # instance name (systemd unit name)
#     port           # web/API port, from spec.config.port
#     configFile     # prometheus.yml generated by expanse-block-run
#     mountPath      # TSDB volume mount point (spec.storage[0].mountPath)
#     retention      # spec.config.retention
#     user           # runtime user (default "expanse-block")
#   }
{ pkgs, name, port, configFile, mountPath, retention, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (monitor/prometheus)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart =
        "${pkgs.prometheus}/bin/prometheus "
        + "--config.file=${configFile} "
        + "--storage.tsdb.path=${mountPath} "
        + "--storage.tsdb.retention.time=${retention} "
        + "--web.listen-address=0.0.0.0:${toString port}";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
