# Block runtime module for share/nfs.
#
# One NFSv4 export per instance served by userspace NFS-Ganesha,
# active/passive over the SINGLETON strategy like share/smb. Ganesha, not
# kernel nfsd: one process per instance with its own port and its own
# client-recovery directory, which lives on the volume so clients can
# reclaim their state on whichever node the export fails over to.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     configFile  # ganesha.conf generated by expanse-block-run (nfs.go)
#     mountPath   # bound volume mount point (spec.storage[0].mountPath)
#   }
{ pkgs, name, configFile, mountPath }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (share/nfs)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      # Root: the VFS FSAL opens files by handle and assumes client uids.
      ExecStartPre = "+${pkgs.coreutils}/bin/install -d -m0700 ${mountPath}/.nfs-state/recovery";
      ExecStart = "${pkgs.nfs-ganesha}/bin/ganesha.nfsd -F -L STDOUT -N NIV_EVENT -f ${configFile} -p /run/expanse-block-${name}.pid";
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      PrivateTmp = true;
    };
  };
}
