# Block runtime module for media/jellyfin.
#
# One jellyfin per instance, active/passive over the SINGLETON strategy like
# security/vaultwarden. Its library database and settings live on the volume;
# expanse-block-run (jellyfin.go) builds the command line and database.xml.
#
# Contract: import and call with:
#   {
#     pkgs  # nixpkgs
#     name  # instance name (systemd unit name)
#     args  # the arguments generated by expanse-block-run
#     user  # runtime user (default "expanse-block")
#   }
{ pkgs, name, args, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (media/jellyfin)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.jellyfin}/bin/jellyfin ${pkgs.lib.escapeShellArgs args}";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
