# Block runtime module for db/mariadb.
#
# One mariadbd per instance, active/passive over the SINGLETON strategy
# like storage/s3. The datadir lives on the volume; my.cnf and the init
# file that converges accounts are generated by expanse-block-run
# (mariadb.go) on every start.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     configFile  # my.cnf generated by expanse-block-run
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, configFile, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (db/mariadb)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.mariadb}/bin/mariadbd --defaults-file=${configFile}";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      # A clean InnoDB shutdown can take a while with a large buffer pool.
      TimeoutStopSec = "120s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
