// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/cluster.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinearReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*LinearReadRequest_GetKey
	//	*LinearReadRequest_ListPrefix
	//	*LinearReadRequest_RevisionOnly
	Query         isLinearReadRequest_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinearReadRequest) Reset() {
	*x = LinearReadRequest{}
	mi := &file_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearReadRequest) ProtoMessage() {}

func (x *LinearReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearReadRequest.ProtoReflect.Descriptor instead.
func (*LinearReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *LinearReadRequest) GetQuery() isLinearReadRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *LinearReadRequest) GetGetKey() string {
	if x != nil {
		if x, ok := x.Query.(*LinearReadRequest_GetKey); ok {
			return x.GetKey
		}
	}
	return ""
}

func (x *LinearReadRequest) GetListPrefix() string {
	if x != nil {
		if x, ok := x.Query.(*LinearReadRequest_ListPrefix); ok {
			return x.ListPrefix
		}
	}
	return ""
}

func (x *LinearReadRequest) GetRevisionOnly() bool {
	if x != nil {
		if x, ok := x.Query.(*LinearReadRequest_RevisionOnly); ok {
			return x.RevisionOnly
		}
	}
	return false
}

type isLinearReadRequest_Query interface {
	isLinearReadRequest_Query()
}

type LinearReadRequest_GetKey struct {
	GetKey string `protobuf:"bytes,1,opt,name=get_key,json=getKey,proto3,oneof"`
}

type LinearReadRequest_ListPrefix struct {
	ListPrefix string `protobuf:"bytes,2,opt,name=list_prefix,json=listPrefix,proto3,oneof"`
}

type LinearReadRequest_RevisionOnly struct {
	RevisionOnly bool `protobuf:"varint,3,opt,name=revision_only,json=revisionOnly,proto3,oneof"`
}

func (*LinearReadRequest_GetKey) isLinearReadRequest_Query() {}

func (*LinearReadRequest_ListPrefix) isLinearReadRequest_Query() {}

func (*LinearReadRequest_RevisionOnly) isLinearReadRequest_Query() {}

type LinearReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LinearReadResponse_Entry
	//	*LinearReadResponse_List
	//	*LinearReadResponse_Revision
	//	*LinearReadResponse_Error
	Result        isLinearReadResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinearReadResponse) Reset() {
	*x = LinearReadResponse{}
	mi := &file_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearReadResponse) ProtoMessage() {}

func (x *LinearReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearReadResponse.ProtoReflect.Descriptor instead.
func (*LinearReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *LinearReadResponse) GetResult() isLinearReadResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LinearReadResponse) GetEntry() *Entry {
	if x != nil {
		if x, ok := x.Result.(*LinearReadResponse_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *LinearReadResponse) GetList() *EntryList {
	if x != nil {
		if x, ok := x.Result.(*LinearReadResponse_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *LinearReadResponse) GetRevision() uint64 {
	if x != nil {
		if x, ok := x.Result.(*LinearReadResponse_Revision); ok {
			return x.Revision
		}
	}
	return 0
}

func (x *LinearReadResponse) GetError() *ErrorDetail {
	if x != nil {
		if x, ok := x.Result.(*LinearReadResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isLinearReadResponse_Result interface {
	isLinearReadResponse_Result()
}

type LinearReadResponse_Entry struct {
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3,oneof"`
}

type LinearReadResponse_List struct {
	List *EntryList `protobuf:"bytes,2,opt,name=list,proto3,oneof"`
}

type LinearReadResponse_Revision struct {
	Revision uint64 `protobuf:"varint,3,opt,name=revision,proto3,oneof"`
}

type LinearReadResponse_Error struct {
	Error *ErrorDetail `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*LinearReadResponse_Entry) isLinearReadResponse_Result() {}

func (*LinearReadResponse_List) isLinearReadResponse_Result() {}

func (*LinearReadResponse_Revision) isLinearReadResponse_Result() {}

func (*LinearReadResponse_Error) isLinearReadResponse_Result() {}

type Entry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Revision        uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	CreatedAtUnixNs int64                  `protobuf:"varint,4,opt,name=created_at_unix_ns,json=createdAtUnixNs,proto3" json:"created_at_unix_ns,omitempty"`
	UpdatedAtUnixNs int64                  `protobuf:"varint,5,opt,name=updated_at_unix_ns,json=updatedAtUnixNs,proto3" json:"updated_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Entry) GetCreatedAtUnixNs() int64 {
	if x != nil {
		return x.CreatedAtUnixNs
	}
	return 0
}

func (x *Entry) GetUpdatedAtUnixNs() int64 {
	if x != nil {
		return x.UpdatedAtUnixNs
	}
	return 0
}

type EntryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryList) Reset() {
	*x = EntryList{}
	mi := &file_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryList) ProtoMessage() {}

func (x *EntryList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryList.ProtoReflect.Descriptor instead.
func (*EntryList) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *EntryList) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ForwardCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ForwardCommandResponse_Revision
	//	*ForwardCommandResponse_Error
	Result        isForwardCommandResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardCommandResponse) Reset() {
	*x = ForwardCommandResponse{}
	mi := &file_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardCommandResponse) ProtoMessage() {}

func (x *ForwardCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardCommandResponse.ProtoReflect.Descriptor instead.
func (*ForwardCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardCommandResponse) GetResult() isForwardCommandResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ForwardCommandResponse) GetRevision() uint64 {
	if x != nil {
		if x, ok := x.Result.(*ForwardCommandResponse_Revision); ok {
			return x.Revision
		}
	}
	return 0
}

func (x *ForwardCommandResponse) GetError() *ErrorDetail {
	if x != nil {
		if x, ok := x.Result.(*ForwardCommandResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isForwardCommandResponse_Result interface {
	isForwardCommandResponse_Result()
}

type ForwardCommandResponse_Revision struct {
	// Revision of the committed state after the command applied.
	Revision uint64 `protobuf:"varint,1,opt,name=revision,proto3,oneof"`
}

type ForwardCommandResponse_Error struct {
	// The typed error from the leader's apply (kind/op/message of
	// internal/errors.Error), so client-side error semantics are
	// identical whether a write ran locally or was forwarded.
	Error *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ForwardCommandResponse_Revision) isForwardCommandResponse_Result() {}

func (*ForwardCommandResponse_Error) isForwardCommandResponse_Result() {}

// ErrorDetail mirrors internal/errors.Error for cross-node transport.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorDetail) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ErrorDetail) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                      // Raft server ID / cert CN
	Csr           []byte                 `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`                                          // PKCS#10 DER; CN must equal node_id
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                                      // expanse-join-… token
	AdvertiseAddr string                 `protobuf:"bytes,4,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"` // Raft addr host:port the joiner binds
	ApiAddr       string                 `protobuf:"bytes,5,opt,name=api_addr,json=apiAddr,proto3" json:"api_addr,omitempty"`                   // public API addr host:port
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`                                        // voter | nonvoter | witness (§4.2)
	Inventory     string                 `protobuf:"bytes,7,opt,name=inventory,proto3" json:"inventory,omitempty"`                              // JSON capabilities/capacity (phase 04)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *JoinRequest) GetApiAddr() string {
	if x != nil {
		return x.ApiAddr
	}
	return ""
}

func (x *JoinRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *JoinRequest) GetInventory() string {
	if x != nil {
		return x.Inventory
	}
	return ""
}

type JoinResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CaCert         []byte                 `protobuf:"bytes,1,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`       // cluster CA cert, PEM
	NodeCert       []byte                 `protobuf:"bytes,2,opt,name=node_cert,json=nodeCert,proto3" json:"node_cert,omitempty"` // freshly signed node cert, PEM
	ClusterId      string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterSecret  []byte                 `protobuf:"bytes,4,opt,name=cluster_secret,json=clusterSecret,proto3" json:"cluster_secret,omitempty"` // 32B; HMAC key for tokens, sealed CA key
	Peers          []*JoinPeer            `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	RaftConfig     string                 `protobuf:"bytes,6,opt,name=raft_config,json=raftConfig,proto3" json:"raft_config,omitempty"` // JSON: heartbeat/election timeouts
	LeaderRaftAddr string                 `protobuf:"bytes,7,opt,name=leader_raft_addr,json=leaderRaftAddr,proto3" json:"leader_raft_addr,omitempty"`
	SealedCaKey    []byte                 `protobuf:"bytes,8,opt,name=sealed_ca_key,json=sealedCaKey,proto3" json:"sealed_ca_key,omitempty"` // CA private key, age-sealed to the cluster secret (§4.4: every node can serve joins when leader)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *JoinResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *JoinResponse) GetNodeCert() []byte {
	if x != nil {
		return x.NodeCert
	}
	return nil
}

func (x *JoinResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *JoinResponse) GetClusterSecret() []byte {
	if x != nil {
		return x.ClusterSecret
	}
	return nil
}

func (x *JoinResponse) GetPeers() []*JoinPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *JoinResponse) GetRaftConfig() string {
	if x != nil {
		return x.RaftConfig
	}
	return ""
}

func (x *JoinResponse) GetLeaderRaftAddr() string {
	if x != nil {
		return x.LeaderRaftAddr
	}
	return ""
}

func (x *JoinResponse) GetSealedCaKey() []byte {
	if x != nil {
		return x.SealedCaKey
	}
	return nil
}

type JoinPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	ApiAddr       string                 `protobuf:"bytes,3,opt,name=api_addr,json=apiAddr,proto3" json:"api_addr,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPeer) Reset() {
	*x = JoinPeer{}
	mi := &file_proto_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPeer) ProtoMessage() {}

func (x *JoinPeer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPeer.ProtoReflect.Descriptor instead.
func (*JoinPeer) Descriptor() ([]byte, []int) {
	return file_proto_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *JoinPeer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinPeer) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *JoinPeer) GetApiAddr() string {
	if x != nil {
		return x.ApiAddr
	}
	return ""
}

func (x *JoinPeer) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_proto_cluster_proto protoreflect.FileDescriptor

const file_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cluster.proto\x12\x12expanse.cluster.v1\x1a\x11proto/store.proto\"\x81\x01\n" +
	"\x11LinearReadRequest\x12\x19\n" +
	"\aget_key\x18\x01 \x01(\tH\x00R\x06getKey\x12!\n" +
	"\vlist_prefix\x18\x02 \x01(\tH\x00R\n" +
	"listPrefix\x12%\n" +
	"\rrevision_only\x18\x03 \x01(\bH\x00R\frevisionOnlyB\a\n" +
	"\x05query\"\xdd\x01\n" +
	"\x12LinearReadResponse\x121\n" +
	"\x05entry\x18\x01 \x01(\v2\x19.expanse.cluster.v1.EntryH\x00R\x05entry\x123\n" +
	"\x04list\x18\x02 \x01(\v2\x1d.expanse.cluster.v1.EntryListH\x00R\x04list\x12\x1c\n" +
	"\brevision\x18\x03 \x01(\x04H\x00R\brevision\x127\n" +
	"\x05error\x18\x04 \x01(\v2\x1f.expanse.cluster.v1.ErrorDetailH\x00R\x05errorB\b\n" +
	"\x06result\"\xa5\x01\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12+\n" +
	"\x12created_at_unix_ns\x18\x04 \x01(\x03R\x0fcreatedAtUnixNs\x12+\n" +
	"\x12updated_at_unix_ns\x18\x05 \x01(\x03R\x0fupdatedAtUnixNs\"@\n" +
	"\tEntryList\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.expanse.cluster.v1.EntryR\aentries\"y\n" +
	"\x16ForwardCommandResponse\x12\x1c\n" +
	"\brevision\x18\x01 \x01(\x04H\x00R\brevision\x127\n" +
	"\x05error\x18\x02 \x01(\v2\x1f.expanse.cluster.v1.ErrorDetailH\x00R\x05errorB\b\n" +
	"\x06result\"K\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc2\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\fR\x03csr\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12%\n" +
	"\x0eadvertise_addr\x18\x04 \x01(\tR\radvertiseAddr\x12\x19\n" +
	"\bapi_addr\x18\x05 \x01(\tR\aapiAddr\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1c\n" +
	"\tinventory\x18\a \x01(\tR\tinventory\"\xad\x02\n" +
	"\fJoinResponse\x12\x17\n" +
	"\aca_cert\x18\x01 \x01(\fR\x06caCert\x12\x1b\n" +
	"\tnode_cert\x18\x02 \x01(\fR\bnodeCert\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12%\n" +
	"\x0ecluster_secret\x18\x04 \x01(\fR\rclusterSecret\x122\n" +
	"\x05peers\x18\x05 \x03(\v2\x1c.expanse.cluster.v1.JoinPeerR\x05peers\x12\x1f\n" +
	"\vraft_config\x18\x06 \x01(\tR\n" +
	"raftConfig\x12(\n" +
	"\x10leader_raft_addr\x18\a \x01(\tR\x0eleaderRaftAddr\x12\"\n" +
	"\rsealed_ca_key\x18\b \x01(\fR\vsealedCaKey\"f\n" +
	"\bJoinPeer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12\x19\n" +
	"\bapi_addr\x18\x03 \x01(\tR\aapiAddr\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role2\xcc\x01\n" +
	"\x14InternalStoreService\x12W\n" +
	"\x0eForwardCommand\x12\x19.expanse.store.v1.Command\x1a*.expanse.cluster.v1.ForwardCommandResponse\x12[\n" +
	"\n" +
	"LinearRead\x12%.expanse.cluster.v1.LinearReadRequest\x1a&.expanse.cluster.v1.LinearReadResponse2X\n" +
	"\vJoinService\x12I\n" +
	"\x04Join\x12\x1f.expanse.cluster.v1.JoinRequest\x1a .expanse.cluster.v1.JoinResponseB\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_cluster_proto_rawDescOnce sync.Once
	file_proto_cluster_proto_rawDescData []byte
)

func file_proto_cluster_proto_rawDescGZIP() []byte {
	file_proto_cluster_proto_rawDescOnce.Do(func() {
		file_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)))
	})
	return file_proto_cluster_proto_rawDescData
}

var file_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_cluster_proto_goTypes = []any{
	(*LinearReadRequest)(nil),      // 0: expanse.cluster.v1.LinearReadRequest
	(*LinearReadResponse)(nil),     // 1: expanse.cluster.v1.LinearReadResponse
	(*Entry)(nil),                  // 2: expanse.cluster.v1.Entry
	(*EntryList)(nil),              // 3: expanse.cluster.v1.EntryList
	(*ForwardCommandResponse)(nil), // 4: expanse.cluster.v1.ForwardCommandResponse
	(*ErrorDetail)(nil),            // 5: expanse.cluster.v1.ErrorDetail
	(*JoinRequest)(nil),            // 6: expanse.cluster.v1.JoinRequest
	(*JoinResponse)(nil),           // 7: expanse.cluster.v1.JoinResponse
	(*JoinPeer)(nil),               // 8: expanse.cluster.v1.JoinPeer
	(*Command)(nil),                // 9: expanse.store.v1.Command
}
var file_proto_cluster_proto_depIdxs = []int32{
	2, // 0: expanse.cluster.v1.LinearReadResponse.entry:type_name -> expanse.cluster.v1.Entry
	3, // 1: expanse.cluster.v1.LinearReadResponse.list:type_name -> expanse.cluster.v1.EntryList
	5, // 2: expanse.cluster.v1.LinearReadResponse.error:type_name -> expanse.cluster.v1.ErrorDetail
	2, // 3: expanse.cluster.v1.EntryList.entries:type_name -> expanse.cluster.v1.Entry
	5, // 4: expanse.cluster.v1.ForwardCommandResponse.error:type_name -> expanse.cluster.v1.ErrorDetail
	8, // 5: expanse.cluster.v1.JoinResponse.peers:type_name -> expanse.cluster.v1.JoinPeer
	9, // 6: expanse.cluster.v1.InternalStoreService.ForwardCommand:input_type -> expanse.store.v1.Command
	0, // 7: expanse.cluster.v1.InternalStoreService.LinearRead:input_type -> expanse.cluster.v1.LinearReadRequest
	6, // 8: expanse.cluster.v1.JoinService.Join:input_type -> expanse.cluster.v1.JoinRequest
	4, // 9: expanse.cluster.v1.InternalStoreService.ForwardCommand:output_type -> expanse.cluster.v1.ForwardCommandResponse
	1, // 10: expanse.cluster.v1.InternalStoreService.LinearRead:output_type -> expanse.cluster.v1.LinearReadResponse
	7, // 11: expanse.cluster.v1.JoinService.Join:output_type -> expanse.cluster.v1.JoinResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_cluster_proto_init() }
func file_proto_cluster_proto_init() {
	if File_proto_cluster_proto != nil {
		return
	}
	file_proto_store_proto_init()
	file_proto_cluster_proto_msgTypes[0].OneofWrappers = []any{
		(*LinearReadRequest_GetKey)(nil),
		(*LinearReadRequest_ListPrefix)(nil),
		(*LinearReadRequest_RevisionOnly)(nil),
	}
	file_proto_cluster_proto_msgTypes[1].OneofWrappers = []any{
		(*LinearReadResponse_Entry)(nil),
		(*LinearReadResponse_List)(nil),
		(*LinearReadResponse_Revision)(nil),
		(*LinearReadResponse_Error)(nil),
	}
	file_proto_cluster_proto_msgTypes[4].OneofWrappers = []any{
		(*ForwardCommandResponse_Revision)(nil),
		(*ForwardCommandResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cluster_proto_rawDesc), len(file_proto_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_cluster_proto_goTypes,
		DependencyIndexes: file_proto_cluster_proto_depIdxs,
		MessageInfos:      file_proto_cluster_proto_msgTypes,
	}.Build()
	File_proto_cluster_proto = out.File
	file_proto_cluster_proto_goTypes = nil
	file_proto_cluster_proto_depIdxs = nil
}
