// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: proto/cluster.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalStoreService_ForwardCommand_FullMethodName = "/expanse.cluster.v1.InternalStoreService/ForwardCommand"
	InternalStoreService_LinearRead_FullMethodName     = "/expanse.cluster.v1.InternalStoreService/LinearRead"
)

// InternalStoreServiceClient is the client API for InternalStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalStoreService is the node-to-node write-forwarding RPC (§4.1
// "Write forwarding"): a follower that receives a write forwards the
// encoded store Command to the leader, which applies it through Raft and
// returns the committed revision. The command bytes are the same wire
// format the Raft log uses, so no re-encoding happens mid-cluster.
type InternalStoreServiceClient interface {
	// ForwardCommand: follower → leader write forwarding (§4.1).
	ForwardCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ForwardCommandResponse, error)
	// LinearRead: follower → leader read forwarding. raft.Barrier only
	// works on the leader, so a follower serving a linearizable read
	// forwards it (same pattern as Consul's consistent reads).
	LinearRead(ctx context.Context, in *LinearReadRequest, opts ...grpc.CallOption) (*LinearReadResponse, error)
}

type internalStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalStoreServiceClient(cc grpc.ClientConnInterface) InternalStoreServiceClient {
	return &internalStoreServiceClient{cc}
}

func (c *internalStoreServiceClient) ForwardCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ForwardCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardCommandResponse)
	err := c.cc.Invoke(ctx, InternalStoreService_ForwardCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalStoreServiceClient) LinearRead(ctx context.Context, in *LinearReadRequest, opts ...grpc.CallOption) (*LinearReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinearReadResponse)
	err := c.cc.Invoke(ctx, InternalStoreService_LinearRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalStoreServiceServer is the server API for InternalStoreService service.
// All implementations must embed UnimplementedInternalStoreServiceServer
// for forward compatibility.
//
// InternalStoreService is the node-to-node write-forwarding RPC (§4.1
// "Write forwarding"): a follower that receives a write forwards the
// encoded store Command to the leader, which applies it through Raft and
// returns the committed revision. The command bytes are the same wire
// format the Raft log uses, so no re-encoding happens mid-cluster.
type InternalStoreServiceServer interface {
	// ForwardCommand: follower → leader write forwarding (§4.1).
	ForwardCommand(context.Context, *Command) (*ForwardCommandResponse, error)
	// LinearRead: follower → leader read forwarding. raft.Barrier only
	// works on the leader, so a follower serving a linearizable read
	// forwards it (same pattern as Consul's consistent reads).
	LinearRead(context.Context, *LinearReadRequest) (*LinearReadResponse, error)
	mustEmbedUnimplementedInternalStoreServiceServer()
}

// UnimplementedInternalStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalStoreServiceServer struct{}

func (UnimplementedInternalStoreServiceServer) ForwardCommand(context.Context, *Command) (*ForwardCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardCommand not implemented")
}
func (UnimplementedInternalStoreServiceServer) LinearRead(context.Context, *LinearReadRequest) (*LinearReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinearRead not implemented")
}
func (UnimplementedInternalStoreServiceServer) mustEmbedUnimplementedInternalStoreServiceServer() {}
func (UnimplementedInternalStoreServiceServer) testEmbeddedByValue()                              {}

// UnsafeInternalStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalStoreServiceServer will
// result in compilation errors.
type UnsafeInternalStoreServiceServer interface {
	mustEmbedUnimplementedInternalStoreServiceServer()
}

func RegisterInternalStoreServiceServer(s grpc.ServiceRegistrar, srv InternalStoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalStoreService_ServiceDesc, srv)
}

func _InternalStoreService_ForwardCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalStoreServiceServer).ForwardCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalStoreService_ForwardCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalStoreServiceServer).ForwardCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalStoreService_LinearRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinearReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalStoreServiceServer).LinearRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalStoreService_LinearRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalStoreServiceServer).LinearRead(ctx, req.(*LinearReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalStoreService_ServiceDesc is the grpc.ServiceDesc for InternalStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "expanse.cluster.v1.InternalStoreService",
	HandlerType: (*InternalStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardCommand",
			Handler:    _InternalStoreService_ForwardCommand_Handler,
		},
		{
			MethodName: "LinearRead",
			Handler:    _InternalStoreService_LinearRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cluster.proto",
}
