// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/network.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VIPScope selects where a VIP is announced.
type VIPScope int32

const (
	VIPScope_VIP_SCOPE_UNSPECIFIED VIPScope = 0
	// Internal VIPs live in 10.43.0.0/16, cluster-only.
	VIPScope_VIP_SCOPE_INTERNAL VIPScope = 1
	// External VIPs are allocated from the user-declared LAN pool and
	// announced on the physical interface (gratuitous ARP).
	VIPScope_VIP_SCOPE_EXTERNAL VIPScope = 2
)

// Enum value maps for VIPScope.
var (
	VIPScope_name = map[int32]string{
		0: "VIP_SCOPE_UNSPECIFIED",
		1: "VIP_SCOPE_INTERNAL",
		2: "VIP_SCOPE_EXTERNAL",
	}
	VIPScope_value = map[string]int32{
		"VIP_SCOPE_UNSPECIFIED": 0,
		"VIP_SCOPE_INTERNAL":    1,
		"VIP_SCOPE_EXTERNAL":    2,
	}
)

func (x VIPScope) Enum() *VIPScope {
	p := new(VIPScope)
	*p = x
	return p
}

func (x VIPScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VIPScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_network_proto_enumTypes[0].Descriptor()
}

func (VIPScope) Type() protoreflect.EnumType {
	return &file_proto_network_proto_enumTypes[0]
}

func (x VIPScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VIPScope.Descriptor instead.
func (VIPScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{0}
}

// WireGuardPeer is the per-node mesh record published to
// /nodes/<id>/network.wgPublicKey (§4.1). The private key never leaves
// the node; only the public key is stored.
type WireGuardPeer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Base64 WireGuard public key.
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Node's primary LAN address (host:port), refreshed on change.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The node's overlay prefix in CIDR form, e.g. "10.42.1.0/24".
	OverlayPrefix string `protobuf:"bytes,4,opt,name=overlay_prefix,json=overlayPrefix,proto3" json:"overlay_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	mi := &file_proto_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{0}
}

func (x *WireGuardPeer) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WireGuardPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetOverlayPrefix() string {
	if x != nil {
		return x.OverlayPrefix
	}
	return ""
}

// VIP is one virtual-IP record (§4.2). The spec/allocator fields are
// written by the controller; Holder is status written by the lease winner.
type VIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address in CIDR form, e.g. "192.168.1.100/24".
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Physical interface to announce on; "" = auto-detect.
	Interface string   `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Scope     VIPScope `protobuf:"varint,3,opt,name=scope,proto3,enum=expanse.network.v1.VIPScope" json:"scope,omitempty"`
	// Owning block, "<namespace>/<name>".
	BlockRef string `protobuf:"bytes,4,opt,name=block_ref,json=blockRef,proto3" json:"block_ref,omitempty"`
	// Current holder node ID (status; empty = unheld).
	Holder        string `protobuf:"bytes,5,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VIP) Reset() {
	*x = VIP{}
	mi := &file_proto_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VIP) ProtoMessage() {}

func (x *VIP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VIP.ProtoReflect.Descriptor instead.
func (*VIP) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{1}
}

func (x *VIP) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VIP) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *VIP) GetScope() VIPScope {
	if x != nil {
		return x.Scope
	}
	return VIPScope_VIP_SCOPE_UNSPECIFIED
}

func (x *VIP) GetBlockRef() string {
	if x != nil {
		return x.BlockRef
	}
	return ""
}

func (x *VIP) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

// VIPPoolConfig declares the external VIP pool in cluster config (§4.2).
type VIPPoolConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inclusive address range, e.g. "192.168.1.100-192.168.1.120".
	Range string `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	// Physical interface for external VIPs; "" = auto-detect.
	ExternalInterface string `protobuf:"bytes,2,opt,name=external_interface,json=externalInterface,proto3" json:"external_interface,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VIPPoolConfig) Reset() {
	*x = VIPPoolConfig{}
	mi := &file_proto_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VIPPoolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VIPPoolConfig) ProtoMessage() {}

func (x *VIPPoolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VIPPoolConfig.ProtoReflect.Descriptor instead.
func (*VIPPoolConfig) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{2}
}

func (x *VIPPoolConfig) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *VIPPoolConfig) GetExternalInterface() string {
	if x != nil {
		return x.ExternalInterface
	}
	return ""
}

var File_proto_network_proto protoreflect.FileDescriptor

const file_proto_network_proto_rawDesc = "" +
	"\n" +
	"\x13proto/network.proto\x12\x12expanse.network.v1\"\x8a\x01\n" +
	"\rWireGuardPeer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12%\n" +
	"\x0eoverlay_prefix\x18\x04 \x01(\tR\roverlayPrefix\"\xa6\x01\n" +
	"\x03VIP\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x122\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x1c.expanse.network.v1.VIPScopeR\x05scope\x12\x1b\n" +
	"\tblock_ref\x18\x04 \x01(\tR\bblockRef\x12\x16\n" +
	"\x06holder\x18\x05 \x01(\tR\x06holder\"T\n" +
	"\rVIPPoolConfig\x12\x14\n" +
	"\x05range\x18\x01 \x01(\tR\x05range\x12-\n" +
	"\x12external_interface\x18\x02 \x01(\tR\x11externalInterface*U\n" +
	"\bVIPScope\x12\x19\n" +
	"\x15VIP_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VIP_SCOPE_INTERNAL\x10\x01\x12\x16\n" +
	"\x12VIP_SCOPE_EXTERNAL\x10\x02B\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_network_proto_rawDescOnce sync.Once
	file_proto_network_proto_rawDescData []byte
)

func file_proto_network_proto_rawDescGZIP() []byte {
	file_proto_network_proto_rawDescOnce.Do(func() {
		file_proto_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)))
	})
	return file_proto_network_proto_rawDescData
}

var file_proto_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_network_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_network_proto_goTypes = []any{
	(VIPScope)(0),         // 0: expanse.network.v1.VIPScope
	(*WireGuardPeer)(nil), // 1: expanse.network.v1.WireGuardPeer
	(*VIP)(nil),           // 2: expanse.network.v1.VIP
	(*VIPPoolConfig)(nil), // 3: expanse.network.v1.VIPPoolConfig
}
var file_proto_network_proto_depIdxs = []int32{
	0, // 0: expanse.network.v1.VIP.scope:type_name -> expanse.network.v1.VIPScope
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_network_proto_init() }
func file_proto_network_proto_init() {
	if File_proto_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_network_proto_goTypes,
		DependencyIndexes: file_proto_network_proto_depIdxs,
		EnumInfos:         file_proto_network_proto_enumTypes,
		MessageInfos:      file_proto_network_proto_msgTypes,
	}.Build()
	File_proto_network_proto = out.File
	file_proto_network_proto_goTypes = nil
	file_proto_network_proto_depIdxs = nil
}
