// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_GetStatus_FullMethodName          = "/expanse.node.v1.NodeService/GetStatus"
	NodeService_GetInventory_FullMethodName       = "/expanse.node.v1.NodeService/GetInventory"
	NodeService_ListResources_FullMethodName      = "/expanse.node.v1.NodeService/ListResources"
	NodeService_GetResource_FullMethodName        = "/expanse.node.v1.NodeService/GetResource"
	NodeService_ApplyResources_FullMethodName     = "/expanse.node.v1.NodeService/ApplyResources"
	NodeService_DeleteResource_FullMethodName     = "/expanse.node.v1.NodeService/DeleteResource"
	NodeService_Reconcile_FullMethodName          = "/expanse.node.v1.NodeService/Reconcile"
	NodeService_StreamEvents_FullMethodName       = "/expanse.node.v1.NodeService/StreamEvents"
	NodeService_GetHealth_FullMethodName          = "/expanse.node.v1.NodeService/GetHealth"
	NodeService_Shutdown_FullMethodName           = "/expanse.node.v1.NodeService/Shutdown"
	NodeService_ListGenerations_FullMethodName    = "/expanse.node.v1.NodeService/ListGenerations"
	NodeService_GetGeneration_FullMethodName      = "/expanse.node.v1.NodeService/GetGeneration"
	NodeService_DiffGenerations_FullMethodName    = "/expanse.node.v1.NodeService/DiffGenerations"
	NodeService_RollbackGeneration_FullMethodName = "/expanse.node.v1.NodeService/RollbackGeneration"
	NodeService_ExportGeneration_FullMethodName   = "/expanse.node.v1.NodeService/ExportGeneration"
	NodeService_ImportGeneration_FullMethodName   = "/expanse.node.v1.NodeService/ImportGeneration"
	NodeService_PutKeyValue_FullMethodName        = "/expanse.node.v1.NodeService/PutKeyValue"
	NodeService_GetKeyValue_FullMethodName        = "/expanse.node.v1.NodeService/GetKeyValue"
	NodeService_DeleteKeyValue_FullMethodName     = "/expanse.node.v1.NodeService/DeleteKeyValue"
	NodeService_ListKeyValue_FullMethodName       = "/expanse.node.v1.NodeService/ListKeyValue"
	NodeService_GetClusterStatus_FullMethodName   = "/expanse.node.v1.NodeService/GetClusterStatus"
	NodeService_HoldLease_FullMethodName          = "/expanse.node.v1.NodeService/HoldLease"
	NodeService_GetLease_FullMethodName           = "/expanse.node.v1.NodeService/GetLease"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService exposes the single-node agent API.
type NodeServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*NodeStatus, error)
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*Inventory, error)
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error)
	ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error)
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReconcileEvent], error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*HealthReport, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	ListGenerations(ctx context.Context, in *ListGenerationsRequest, opts ...grpc.CallOption) (*ListGenerationsResponse, error)
	GetGeneration(ctx context.Context, in *GetGenerationRequest, opts ...grpc.CallOption) (*GenerationInfo, error)
	DiffGenerations(ctx context.Context, in *DiffGenerationsRequest, opts ...grpc.CallOption) (*DiffGenerationsResponse, error)
	RollbackGeneration(ctx context.Context, in *RollbackGenerationRequest, opts ...grpc.CallOption) (*RollbackGenerationResponse, error)
	// ExportGeneration/ImportGeneration (Phase 8 X4): the current desired
	// state as a canonical snapshot, for feeding an external backup tool's
	// stdin and restoring from it. Mechanically the same append-only
	// convergence Rollback does, just sourced from bytes, not a stored
	// generation number.
	ExportGeneration(ctx context.Context, in *ExportGenerationRequest, opts ...grpc.CallOption) (*ExportGenerationResponse, error)
	ImportGeneration(ctx context.Context, in *ImportGenerationRequest, opts ...grpc.CallOption) (*ImportGenerationResponse, error)
	// KV access to the node's store. In cluster mode a Put goes through
	// Raft (unavailable when degraded, §4.10.3); Get is linearizable by
	// default, `stale` serves the local FSM copy.
	PutKeyValue(ctx context.Context, in *PutKeyValueRequest, opts ...grpc.CallOption) (*PutKeyValueResponse, error)
	GetKeyValue(ctx context.Context, in *GetKeyValueRequest, opts ...grpc.CallOption) (*GetKeyValueResponse, error)
	DeleteKeyValue(ctx context.Context, in *DeleteKeyValueRequest, opts ...grpc.CallOption) (*DeleteKeyValueResponse, error)
	// ListKeyValue: prefix scan (linearizable unless stale).
	ListKeyValue(ctx context.Context, in *ListKeyValueRequest, opts ...grpc.CallOption) (*ListKeyValueResponse, error)
	// GetClusterStatus renders the §5 cluster report from the local
	// store (linearizable reads forward to the leader when follower).
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	// Leases (§4.3): HoldLease acquires (or takes over an expired lease)
	// and holds it server-side — renewing at TTL/3 and closing the lease
	// on renewal failure — streaming lifecycle events with wall-clock
	// timestamps until the lease is lost or the client disconnects. The
	// event timestamps are the guard-band evidence (§4.3 safety
	// argument: old holder stops before TTL, new holder starts after).
	HoldLease(ctx context.Context, in *HoldLeaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error)
	// GetLease reports the stored lease state (even if expired).
	GetLease(ctx context.Context, in *GetLeaseRequest, opts ...grpc.CallOption) (*LeaseInfo, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*Inventory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Inventory)
	err := c.cc.Invoke(ctx, NodeService_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, NodeService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resource)
	err := c.cc.Invoke(ctx, NodeService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResourcesResponse)
	err := c.cc.Invoke(ctx, NodeService_ApplyResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReconcileEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_Reconcile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReconcileRequest, ReconcileEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ReconcileClient = grpc.ServerStreamingClient[ReconcileEvent]

func (c *nodeServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *nodeServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*HealthReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReport)
	err := c.cc.Invoke(ctx, NodeService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, NodeService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListGenerations(ctx context.Context, in *ListGenerationsRequest, opts ...grpc.CallOption) (*ListGenerationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGenerationsResponse)
	err := c.cc.Invoke(ctx, NodeService_ListGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetGeneration(ctx context.Context, in *GetGenerationRequest, opts ...grpc.CallOption) (*GenerationInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationInfo)
	err := c.cc.Invoke(ctx, NodeService_GetGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DiffGenerations(ctx context.Context, in *DiffGenerationsRequest, opts ...grpc.CallOption) (*DiffGenerationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffGenerationsResponse)
	err := c.cc.Invoke(ctx, NodeService_DiffGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RollbackGeneration(ctx context.Context, in *RollbackGenerationRequest, opts ...grpc.CallOption) (*RollbackGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackGenerationResponse)
	err := c.cc.Invoke(ctx, NodeService_RollbackGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ExportGeneration(ctx context.Context, in *ExportGenerationRequest, opts ...grpc.CallOption) (*ExportGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportGenerationResponse)
	err := c.cc.Invoke(ctx, NodeService_ExportGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ImportGeneration(ctx context.Context, in *ImportGenerationRequest, opts ...grpc.CallOption) (*ImportGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportGenerationResponse)
	err := c.cc.Invoke(ctx, NodeService_ImportGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) PutKeyValue(ctx context.Context, in *PutKeyValueRequest, opts ...grpc.CallOption) (*PutKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutKeyValueResponse)
	err := c.cc.Invoke(ctx, NodeService_PutKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetKeyValue(ctx context.Context, in *GetKeyValueRequest, opts ...grpc.CallOption) (*GetKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyValueResponse)
	err := c.cc.Invoke(ctx, NodeService_GetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteKeyValue(ctx context.Context, in *DeleteKeyValueRequest, opts ...grpc.CallOption) (*DeleteKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyValueResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListKeyValue(ctx context.Context, in *ListKeyValueRequest, opts ...grpc.CallOption) (*ListKeyValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeyValueResponse)
	err := c.cc.Invoke(ctx, NodeService_ListKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, NodeService_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HoldLease(ctx context.Context, in *HoldLeaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_HoldLease_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HoldLeaseRequest, LeaseEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_HoldLeaseClient = grpc.ServerStreamingClient[LeaseEvent]

func (c *nodeServiceClient) GetLease(ctx context.Context, in *GetLeaseRequest, opts ...grpc.CallOption) (*LeaseInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseInfo)
	err := c.cc.Invoke(ctx, NodeService_GetLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService exposes the single-node agent API.
type NodeServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*NodeStatus, error)
	GetInventory(context.Context, *GetInventoryRequest) (*Inventory, error)
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	GetResource(context.Context, *GetResourceRequest) (*Resource, error)
	ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error)
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	Reconcile(*ReconcileRequest, grpc.ServerStreamingServer[ReconcileEvent]) error
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	GetHealth(context.Context, *GetHealthRequest) (*HealthReport, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	ListGenerations(context.Context, *ListGenerationsRequest) (*ListGenerationsResponse, error)
	GetGeneration(context.Context, *GetGenerationRequest) (*GenerationInfo, error)
	DiffGenerations(context.Context, *DiffGenerationsRequest) (*DiffGenerationsResponse, error)
	RollbackGeneration(context.Context, *RollbackGenerationRequest) (*RollbackGenerationResponse, error)
	// ExportGeneration/ImportGeneration (Phase 8 X4): the current desired
	// state as a canonical snapshot, for feeding an external backup tool's
	// stdin and restoring from it. Mechanically the same append-only
	// convergence Rollback does, just sourced from bytes, not a stored
	// generation number.
	ExportGeneration(context.Context, *ExportGenerationRequest) (*ExportGenerationResponse, error)
	ImportGeneration(context.Context, *ImportGenerationRequest) (*ImportGenerationResponse, error)
	// KV access to the node's store. In cluster mode a Put goes through
	// Raft (unavailable when degraded, §4.10.3); Get is linearizable by
	// default, `stale` serves the local FSM copy.
	PutKeyValue(context.Context, *PutKeyValueRequest) (*PutKeyValueResponse, error)
	GetKeyValue(context.Context, *GetKeyValueRequest) (*GetKeyValueResponse, error)
	DeleteKeyValue(context.Context, *DeleteKeyValueRequest) (*DeleteKeyValueResponse, error)
	// ListKeyValue: prefix scan (linearizable unless stale).
	ListKeyValue(context.Context, *ListKeyValueRequest) (*ListKeyValueResponse, error)
	// GetClusterStatus renders the §5 cluster report from the local
	// store (linearizable reads forward to the leader when follower).
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	// Leases (§4.3): HoldLease acquires (or takes over an expired lease)
	// and holds it server-side — renewing at TTL/3 and closing the lease
	// on renewal failure — streaming lifecycle events with wall-clock
	// timestamps until the lease is lost or the client disconnects. The
	// event timestamps are the guard-band evidence (§4.3 safety
	// argument: old holder stops before TTL, new holder starts after).
	HoldLease(*HoldLeaseRequest, grpc.ServerStreamingServer[LeaseEvent]) error
	// GetLease reports the stored lease state (even if expired).
	GetLease(context.Context, *GetLeaseRequest) (*LeaseInfo, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) GetStatus(context.Context, *GetStatusRequest) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNodeServiceServer) GetInventory(context.Context, *GetInventoryRequest) (*Inventory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedNodeServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedNodeServiceServer) GetResource(context.Context, *GetResourceRequest) (*Resource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedNodeServiceServer) ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyResources not implemented")
}
func (UnimplementedNodeServiceServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedNodeServiceServer) Reconcile(*ReconcileRequest, grpc.ServerStreamingServer[ReconcileEvent]) error {
	return status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedNodeServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedNodeServiceServer) GetHealth(context.Context, *GetHealthRequest) (*HealthReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedNodeServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedNodeServiceServer) ListGenerations(context.Context, *ListGenerationsRequest) (*ListGenerationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGenerations not implemented")
}
func (UnimplementedNodeServiceServer) GetGeneration(context.Context, *GetGenerationRequest) (*GenerationInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeneration not implemented")
}
func (UnimplementedNodeServiceServer) DiffGenerations(context.Context, *DiffGenerationsRequest) (*DiffGenerationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffGenerations not implemented")
}
func (UnimplementedNodeServiceServer) RollbackGeneration(context.Context, *RollbackGenerationRequest) (*RollbackGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackGeneration not implemented")
}
func (UnimplementedNodeServiceServer) ExportGeneration(context.Context, *ExportGenerationRequest) (*ExportGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportGeneration not implemented")
}
func (UnimplementedNodeServiceServer) ImportGeneration(context.Context, *ImportGenerationRequest) (*ImportGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportGeneration not implemented")
}
func (UnimplementedNodeServiceServer) PutKeyValue(context.Context, *PutKeyValueRequest) (*PutKeyValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutKeyValue not implemented")
}
func (UnimplementedNodeServiceServer) GetKeyValue(context.Context, *GetKeyValueRequest) (*GetKeyValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyValue not implemented")
}
func (UnimplementedNodeServiceServer) DeleteKeyValue(context.Context, *DeleteKeyValueRequest) (*DeleteKeyValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKeyValue not implemented")
}
func (UnimplementedNodeServiceServer) ListKeyValue(context.Context, *ListKeyValueRequest) (*ListKeyValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeyValue not implemented")
}
func (UnimplementedNodeServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedNodeServiceServer) HoldLease(*HoldLeaseRequest, grpc.ServerStreamingServer[LeaseEvent]) error {
	return status.Error(codes.Unimplemented, "method HoldLease not implemented")
}
func (UnimplementedNodeServiceServer) GetLease(context.Context, *GetLeaseRequest) (*LeaseInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLease not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ApplyResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ApplyResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ApplyResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ApplyResources(ctx, req.(*ApplyResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Reconcile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReconcileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).Reconcile(m, &grpc.GenericServerStream[ReconcileRequest, ReconcileEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ReconcileServer = grpc.ServerStreamingServer[ReconcileEvent]

func _NodeService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _NodeService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGenerationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListGenerations(ctx, req.(*ListGenerationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetGeneration(ctx, req.(*GetGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DiffGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffGenerationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DiffGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DiffGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DiffGenerations(ctx, req.(*DiffGenerationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RollbackGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RollbackGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RollbackGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RollbackGeneration(ctx, req.(*RollbackGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ExportGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ExportGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ExportGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ExportGeneration(ctx, req.(*ExportGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ImportGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ImportGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ImportGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ImportGeneration(ctx, req.(*ImportGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_PutKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).PutKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_PutKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).PutKeyValue(ctx, req.(*PutKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetKeyValue(ctx, req.(*GetKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteKeyValue(ctx, req.(*DeleteKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListKeyValue(ctx, req.(*ListKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HoldLease_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HoldLeaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).HoldLease(m, &grpc.GenericServerStream[HoldLeaseRequest, LeaseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_HoldLeaseServer = grpc.ServerStreamingServer[LeaseEvent]

func _NodeService_GetLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetLease(ctx, req.(*GetLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "expanse.node.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _NodeService_GetStatus_Handler,
		},
		{
			MethodName: "GetInventory",
			Handler:    _NodeService_GetInventory_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _NodeService_ListResources_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _NodeService_GetResource_Handler,
		},
		{
			MethodName: "ApplyResources",
			Handler:    _NodeService_ApplyResources_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _NodeService_DeleteResource_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _NodeService_GetHealth_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _NodeService_Shutdown_Handler,
		},
		{
			MethodName: "ListGenerations",
			Handler:    _NodeService_ListGenerations_Handler,
		},
		{
			MethodName: "GetGeneration",
			Handler:    _NodeService_GetGeneration_Handler,
		},
		{
			MethodName: "DiffGenerations",
			Handler:    _NodeService_DiffGenerations_Handler,
		},
		{
			MethodName: "RollbackGeneration",
			Handler:    _NodeService_RollbackGeneration_Handler,
		},
		{
			MethodName: "ExportGeneration",
			Handler:    _NodeService_ExportGeneration_Handler,
		},
		{
			MethodName: "ImportGeneration",
			Handler:    _NodeService_ImportGeneration_Handler,
		},
		{
			MethodName: "PutKeyValue",
			Handler:    _NodeService_PutKeyValue_Handler,
		},
		{
			MethodName: "GetKeyValue",
			Handler:    _NodeService_GetKeyValue_Handler,
		},
		{
			MethodName: "DeleteKeyValue",
			Handler:    _NodeService_DeleteKeyValue_Handler,
		},
		{
			MethodName: "ListKeyValue",
			Handler:    _NodeService_ListKeyValue_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _NodeService_GetClusterStatus_Handler,
		},
		{
			MethodName: "GetLease",
			Handler:    _NodeService_GetLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Reconcile",
			Handler:       _NodeService_Reconcile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _NodeService_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HoldLease",
			Handler:       _NodeService_HoldLease_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/node.proto",
}
