// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_HEALTHY     Health = 1
	Health_HEALTH_DEGRADED    Health = 2
	Health_HEALTH_UNHEALTHY   Health = 3
	Health_HEALTH_UNKNOWN     Health = 4
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_DEGRADED",
		3: "HEALTH_UNHEALTHY",
		4: "HEALTH_UNKNOWN",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_HEALTHY":     1,
		"HEALTH_DEGRADED":    2,
		"HEALTH_UNHEALTHY":   3,
		"HEALTH_UNKNOWN":     4,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type NodeStatus_Status int32

const (
	NodeStatus_STATUS_UNSPECIFIED NodeStatus_Status = 0
	NodeStatus_STATUS_IDLE        NodeStatus_Status = 1
	NodeStatus_STATUS_RECONCILING NodeStatus_Status = 2
	NodeStatus_STATUS_DEGRADED    NodeStatus_Status = 3
	NodeStatus_STATUS_ERROR       NodeStatus_Status = 4
)

// Enum value maps for NodeStatus_Status.
var (
	NodeStatus_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_IDLE",
		2: "STATUS_RECONCILING",
		3: "STATUS_DEGRADED",
		4: "STATUS_ERROR",
	}
	NodeStatus_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_IDLE":        1,
		"STATUS_RECONCILING": 2,
		"STATUS_DEGRADED":    3,
		"STATUS_ERROR":       4,
	}
)

func (x NodeStatus_Status) Enum() *NodeStatus_Status {
	p := new(NodeStatus_Status)
	*p = x
	return p
}

func (x NodeStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[1].Descriptor()
}

func (NodeStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[1]
}

func (x NodeStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus_Status.Descriptor instead.
func (NodeStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1, 0}
}

type HealthReport_OverallStatus int32

const (
	HealthReport_OVERALL_UNSPECIFIED HealthReport_OverallStatus = 0
	HealthReport_OVERALL_HEALTHY     HealthReport_OverallStatus = 1
	HealthReport_OVERALL_DEGRADED    HealthReport_OverallStatus = 2
	HealthReport_OVERALL_UNHEALTHY   HealthReport_OverallStatus = 3
)

// Enum value maps for HealthReport_OverallStatus.
var (
	HealthReport_OverallStatus_name = map[int32]string{
		0: "OVERALL_UNSPECIFIED",
		1: "OVERALL_HEALTHY",
		2: "OVERALL_DEGRADED",
		3: "OVERALL_UNHEALTHY",
	}
	HealthReport_OverallStatus_value = map[string]int32{
		"OVERALL_UNSPECIFIED": 0,
		"OVERALL_HEALTHY":     1,
		"OVERALL_DEGRADED":    2,
		"OVERALL_UNHEALTHY":   3,
	}
)

func (x HealthReport_OverallStatus) Enum() *HealthReport_OverallStatus {
	p := new(HealthReport_OverallStatus)
	*p = x
	return p
}

func (x HealthReport_OverallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthReport_OverallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[2].Descriptor()
}

func (HealthReport_OverallStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[2]
}

func (x HealthReport_OverallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthReport_OverallStatus.Descriptor instead.
func (HealthReport_OverallStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{24, 0}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type NodeStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status             NodeStatus_Status      `protobuf:"varint,2,opt,name=status,proto3,enum=expanse.node.v1.NodeStatus_Status" json:"status,omitempty"`
	TickCount          int64                  `protobuf:"varint,3,opt,name=tick_count,json=tickCount,proto3" json:"tick_count,omitempty"`
	LastTickUnixNs     int64                  `protobuf:"varint,4,opt,name=last_tick_unix_ns,json=lastTickUnixNs,proto3" json:"last_tick_unix_ns,omitempty"`
	LastTickDurationMs float64                `protobuf:"fixed64,5,opt,name=last_tick_duration_ms,json=lastTickDurationMs,proto3" json:"last_tick_duration_ms,omitempty"`
	ResourcesTotal     int64                  `protobuf:"varint,6,opt,name=resources_total,json=resourcesTotal,proto3" json:"resources_total,omitempty"`
	ChangesApplied     int64                  `protobuf:"varint,7,opt,name=changes_applied,json=changesApplied,proto3" json:"changes_applied,omitempty"`
	Failures           int64                  `protobuf:"varint,8,opt,name=failures,proto3" json:"failures,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetStatus() NodeStatus_Status {
	if x != nil {
		return x.Status
	}
	return NodeStatus_STATUS_UNSPECIFIED
}

func (x *NodeStatus) GetTickCount() int64 {
	if x != nil {
		return x.TickCount
	}
	return 0
}

func (x *NodeStatus) GetLastTickUnixNs() int64 {
	if x != nil {
		return x.LastTickUnixNs
	}
	return 0
}

func (x *NodeStatus) GetLastTickDurationMs() float64 {
	if x != nil {
		return x.LastTickDurationMs
	}
	return 0
}

func (x *NodeStatus) GetResourcesTotal() int64 {
	if x != nil {
		return x.ResourcesTotal
	}
	return 0
}

func (x *NodeStatus) GetChangesApplied() int64 {
	if x != nil {
		return x.ChangesApplied
	}
	return 0
}

func (x *NodeStatus) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

type Inventory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             *OSInfo                `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Cpu            *CPUInfo               `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory         *MemoryInfo            `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks          []*DiskInfo            `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics           []*NICInfo             `protobuf:"bytes,7,rep,name=nics,proto3" json:"nics,omitempty"`
	Gpus           []*GPUInfo             `protobuf:"bytes,8,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Virtualization string                 `protobuf:"bytes,9,opt,name=virtualization,proto3" json:"virtualization,omitempty"`
	Tpm            *TPMInfo               `protobuf:"bytes,10,opt,name=tpm,proto3" json:"tpm,omitempty"`
	Capabilities   []string               `protobuf:"bytes,11,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *Inventory) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Inventory) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Inventory) GetOs() *OSInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Inventory) GetCpu() *CPUInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Inventory) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Inventory) GetDisks() []*DiskInfo {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Inventory) GetNics() []*NICInfo {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *Inventory) GetGpus() []*GPUInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Inventory) GetVirtualization() string {
	if x != nil {
		return x.Virtualization
	}
	return ""
}

func (x *Inventory) GetTpm() *TPMInfo {
	if x != nil {
		return x.Tpm
	}
	return nil
}

func (x *Inventory) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type OSInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kernel            string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	SystemClosurePath string                 `protobuf:"bytes,4,opt,name=system_closure_path,json=systemClosurePath,proto3" json:"system_closure_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *OSInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *OSInfo) GetSystemClosurePath() string {
	if x != nil {
		return x.SystemClosurePath
	}
	return ""
}

type CPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Cores         int64                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       int64                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Mhz           float64                `protobuf:"fixed64,4,opt,name=mhz,proto3" json:"mhz,omitempty"`
	Flags         []string               `protobuf:"bytes,5,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *CPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CPUInfo) GetCores() int64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUInfo) GetThreads() int64 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUInfo) GetMhz() float64 {
	if x != nil {
		return x.Mhz
	}
	return 0
}

func (x *CPUInfo) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available     int64                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	SwapTotal     int64                  `protobuf:"varint,3,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapAvailable int64                  `protobuf:"varint,4,opt,name=swap_available,json=swapAvailable,proto3" json:"swap_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryInfo) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryInfo) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryInfo) GetSwapAvailable() int64 {
	if x != nil {
		return x.SwapAvailable
	}
	return 0
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Rotational    bool                   `protobuf:"varint,5,opt,name=rotational,proto3" json:"rotational,omitempty"`
	SmartStatus   string                 `protobuf:"bytes,6,opt,name=smart_status,json=smartStatus,proto3" json:"smart_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *DiskInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiskInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DiskInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DiskInfo) GetRotational() bool {
	if x != nil {
		return x.Rotational
	}
	return false
}

func (x *DiskInfo) GetSmartStatus() string {
	if x != nil {
		return x.SmartStatus
	}
	return ""
}

type NICInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Speed         int64                  `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Up            bool                   `protobuf:"varint,5,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NICInfo) Reset() {
	*x = NICInfo{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NICInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NICInfo) ProtoMessage() {}

func (x *NICInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NICInfo.ProtoReflect.Descriptor instead.
func (*NICInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *NICInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NICInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NICInfo) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *NICInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NICInfo) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type GPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Vram          int64                  `protobuf:"varint,3,opt,name=vram,proto3" json:"vram,omitempty"`
	Driver        string                 `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	PciId         string                 `protobuf:"bytes,5,opt,name=pci_id,json=pciId,proto3" json:"pci_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *GPUInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUInfo) GetVram() int64 {
	if x != nil {
		return x.Vram
	}
	return 0
}

func (x *GPUInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GPUInfo) GetPciId() string {
	if x != nil {
		return x.PciId
	}
	return ""
}

type TPMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TPMInfo) Reset() {
	*x = TPMInfo{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPMInfo) ProtoMessage() {}

func (x *TPMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPMInfo.ProtoReflect.Descriptor instead.
func (*TPMInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *TPMInfo) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *TPMInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *ListResourcesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type Resource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DesiredState    string                 `protobuf:"bytes,3,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	ObservedState   string                 `protobuf:"bytes,4,opt,name=observed_state,json=observedState,proto3" json:"observed_state,omitempty"`
	Health          Health                 `protobuf:"varint,5,opt,name=health,proto3,enum=expanse.node.v1.Health" json:"health,omitempty"`
	UpdatedAtUnixNs int64                  `protobuf:"varint,6,opt,name=updated_at_unix_ns,json=updatedAtUnixNs,proto3" json:"updated_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *Resource) GetObservedState() string {
	if x != nil {
		return x.ObservedState
	}
	return ""
}

func (x *Resource) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *Resource) GetUpdatedAtUnixNs() int64 {
	if x != nil {
		return x.UpdatedAtUnixNs
	}
	return 0
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *GetResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApplyResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourcesRequest) Reset() {
	*x = ApplyResourcesRequest{}
	mi := &file_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourcesRequest) ProtoMessage() {}

func (x *ApplyResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourcesRequest.ProtoReflect.Descriptor instead.
func (*ApplyResourcesRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyResourcesRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ApplyResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       int64                  `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Failed        int64                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResourcesResponse) Reset() {
	*x = ApplyResourcesResponse{}
	mi := &file_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResourcesResponse) ProtoMessage() {}

func (x *ApplyResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResourcesResponse.ProtoReflect.Descriptor instead.
func (*ApplyResourcesResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *ApplyResourcesResponse) GetApplied() int64 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *ApplyResourcesResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ApplyResourcesResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResourceResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DryRun        bool                   `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_proto_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{19}
}

func (x *ReconcileRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ReconcileEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProgressPct   float64                `protobuf:"fixed64,3,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileEvent) Reset() {
	*x = ReconcileEvent{}
	mi := &file_proto_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileEvent) ProtoMessage() {}

func (x *ReconcileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileEvent.ProtoReflect.Descriptor instead.
func (*ReconcileEvent) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{20}
}

func (x *ReconcileEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ReconcileEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReconcileEvent) GetProgressPct() float64 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{21}
}

func (x *StreamEventsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload         string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampUnixNs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{22}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_proto_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{23}
}

type HealthReport struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Checks        []*CheckResult             `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	Overall       HealthReport_OverallStatus `protobuf:"varint,2,opt,name=overall,proto3,enum=expanse.node.v1.HealthReport_OverallStatus" json:"overall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_proto_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{24}
}

func (x *HealthReport) GetChecks() []*CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *HealthReport) GetOverall() HealthReport_OverallStatus {
	if x != nil {
		return x.Overall
	}
	return HealthReport_OVERALL_UNSPECIFIED
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        Health                 `protobuf:"varint,2,opt,name=status,proto3,enum=expanse.node.v1.Health" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TookMs        int64                  `protobuf:"varint,5,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_proto_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{25}
}

func (x *CheckResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckResult) GetStatus() Health {
	if x != nil {
		return x.Status
	}
	return Health_HEALTH_UNSPECIFIED
}

func (x *CheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckResult) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *CheckResult) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{26}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{27}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\x0fexpanse.node.v1\"\x12\n" +
	"\x10GetStatusRequest\"\xbe\x03\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".expanse.node.v1.NodeStatus.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"tick_count\x18\x03 \x01(\x03R\ttickCount\x12)\n" +
	"\x11last_tick_unix_ns\x18\x04 \x01(\x03R\x0elastTickUnixNs\x121\n" +
	"\x15last_tick_duration_ms\x18\x05 \x01(\x01R\x12lastTickDurationMs\x12'\n" +
	"\x0fresources_total\x18\x06 \x01(\x03R\x0eresourcesTotal\x12'\n" +
	"\x0fchanges_applied\x18\a \x01(\x03R\x0echangesApplied\x12\x1a\n" +
	"\bfailures\x18\b \x01(\x03R\bfailures\"p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATUS_IDLE\x10\x01\x12\x16\n" +
	"\x12STATUS_RECONCILING\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x03\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x04\"\x15\n" +
	"\x13GetInventoryRequest\"\xcf\x03\n" +
	"\tInventory\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12'\n" +
	"\x02os\x18\x03 \x01(\v2\x17.expanse.node.v1.OSInfoR\x02os\x12*\n" +
	"\x03cpu\x18\x04 \x01(\v2\x18.expanse.node.v1.CPUInfoR\x03cpu\x123\n" +
	"\x06memory\x18\x05 \x01(\v2\x1b.expanse.node.v1.MemoryInfoR\x06memory\x12/\n" +
	"\x05disks\x18\x06 \x03(\v2\x19.expanse.node.v1.DiskInfoR\x05disks\x12,\n" +
	"\x04nics\x18\a \x03(\v2\x18.expanse.node.v1.NICInfoR\x04nics\x12,\n" +
	"\x04gpus\x18\b \x03(\v2\x18.expanse.node.v1.GPUInfoR\x04gpus\x12&\n" +
	"\x0evirtualization\x18\t \x01(\tR\x0evirtualization\x12*\n" +
	"\x03tpm\x18\n" +
	" \x01(\v2\x18.expanse.node.v1.TPMInfoR\x03tpm\x12\"\n" +
	"\fcapabilities\x18\v \x03(\tR\fcapabilities\"~\n" +
	"\x06OSInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12.\n" +
	"\x13system_closure_path\x18\x04 \x01(\tR\x11systemClosurePath\"w\n" +
	"\aCPUInfo\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x03R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x03R\athreads\x12\x10\n" +
	"\x03mhz\x18\x04 \x01(\x01R\x03mhz\x12\x14\n" +
	"\x05flags\x18\x05 \x03(\tR\x05flags\"\x86\x01\n" +
	"\n" +
	"MemoryInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x03R\tavailable\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x03 \x01(\x03R\tswapTotal\x12%\n" +
	"\x0eswap_available\x18\x04 \x01(\x03R\rswapAvailable\"\xa3\x01\n" +
	"\bDiskInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1e\n" +
	"\n" +
	"rotational\x18\x05 \x01(\bR\n" +
	"rotational\x12!\n" +
	"\fsmart_status\x18\x06 \x01(\tR\vsmartStatus\"s\n" +
	"\aNICInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x03R\x05speed\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x0e\n" +
	"\x02up\x18\x05 \x01(\bR\x02up\"z\n" +
	"\aGPUInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04vram\x18\x03 \x01(\x03R\x04vram\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x12\x15\n" +
	"\x06pci_id\x18\x05 \x01(\tR\x05pciId\"=\n" +
	"\aTPMInfo\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\".\n" +
	"\x14ListResourcesRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\xd8\x01\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rdesired_state\x18\x03 \x01(\tR\fdesiredState\x12%\n" +
	"\x0eobserved_state\x18\x04 \x01(\tR\robservedState\x12/\n" +
	"\x06health\x18\x05 \x01(\x0e2\x17.expanse.node.v1.HealthR\x06health\x12+\n" +
	"\x12updated_at_unix_ns\x18\x06 \x01(\x03R\x0fupdatedAtUnixNs\"P\n" +
	"\x15ListResourcesResponse\x127\n" +
	"\tresources\x18\x01 \x03(\v2\x19.expanse.node.v1.ResourceR\tresources\"$\n" +
	"\x12GetResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x15ApplyResourcesRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\"b\n" +
	"\x16ApplyResourcesResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\x03R\aapplied\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x03R\x06failed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"'\n" +
	"\x15DeleteResourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteResourceResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"+\n" +
	"\x10ReconcileRequest\x12\x17\n" +
	"\adry_run\x18\x01 \x01(\bR\x06dryRun\"c\n" +
	"\x0eReconcileEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fprogress_pct\x18\x03 \x01(\x01R\vprogressPct\"-\n" +
	"\x13StreamEventsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"a\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12*\n" +
	"\x11timestamp_unix_ns\x18\x03 \x01(\x03R\x0ftimestampUnixNs\"\x12\n" +
	"\x10GetHealthRequest\"\xf7\x01\n" +
	"\fHealthReport\x124\n" +
	"\x06checks\x18\x01 \x03(\v2\x1c.expanse.node.v1.CheckResultR\x06checks\x12E\n" +
	"\aoverall\x18\x02 \x01(\x0e2+.expanse.node.v1.HealthReport.OverallStatusR\aoverall\"j\n" +
	"\rOverallStatus\x12\x17\n" +
	"\x13OVERALL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOVERALL_HEALTHY\x10\x01\x12\x14\n" +
	"\x10OVERALL_DEGRADED\x10\x02\x12\x15\n" +
	"\x11OVERALL_UNHEALTHY\x10\x03\"\x86\x02\n" +
	"\vCheckResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.expanse.node.v1.HealthR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12C\n" +
	"\adetails\x18\x04 \x03(\v2).expanse.node.v1.CheckResult.DetailsEntryR\adetails\x12\x17\n" +
	"\atook_ms\x18\x05 \x01(\x03R\x06tookMs\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fShutdownRequest\"F\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*s\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x03\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x042\xe4\x06\n" +
	"\vNodeService\x12K\n" +
	"\tGetStatus\x12!.expanse.node.v1.GetStatusRequest\x1a\x1b.expanse.node.v1.NodeStatus\x12P\n" +
	"\fGetInventory\x12$.expanse.node.v1.GetInventoryRequest\x1a\x1a.expanse.node.v1.Inventory\x12^\n" +
	"\rListResources\x12%.expanse.node.v1.ListResourcesRequest\x1a&.expanse.node.v1.ListResourcesResponse\x12M\n" +
	"\vGetResource\x12#.expanse.node.v1.GetResourceRequest\x1a\x19.expanse.node.v1.Resource\x12a\n" +
	"\x0eApplyResources\x12&.expanse.node.v1.ApplyResourcesRequest\x1a'.expanse.node.v1.ApplyResourcesResponse\x12a\n" +
	"\x0eDeleteResource\x12&.expanse.node.v1.DeleteResourceRequest\x1a'.expanse.node.v1.DeleteResourceResponse\x12Q\n" +
	"\tReconcile\x12!.expanse.node.v1.ReconcileRequest\x1a\x1f.expanse.node.v1.ReconcileEvent0\x01\x12N\n" +
	"\fStreamEvents\x12$.expanse.node.v1.StreamEventsRequest\x1a\x16.expanse.node.v1.Event0\x01\x12M\n" +
	"\tGetHealth\x12!.expanse.node.v1.GetHealthRequest\x1a\x1d.expanse.node.v1.HealthReport\x12O\n" +
	"\bShutdown\x12 .expanse.node.v1.ShutdownRequest\x1a!.expanse.node.v1.ShutdownResponseB\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_node_proto_goTypes = []any{
	(Health)(0),                     // 0: expanse.node.v1.Health
	(NodeStatus_Status)(0),          // 1: expanse.node.v1.NodeStatus.Status
	(HealthReport_OverallStatus)(0), // 2: expanse.node.v1.HealthReport.OverallStatus
	(*GetStatusRequest)(nil),        // 3: expanse.node.v1.GetStatusRequest
	(*NodeStatus)(nil),              // 4: expanse.node.v1.NodeStatus
	(*GetInventoryRequest)(nil),     // 5: expanse.node.v1.GetInventoryRequest
	(*Inventory)(nil),               // 6: expanse.node.v1.Inventory
	(*OSInfo)(nil),                  // 7: expanse.node.v1.OSInfo
	(*CPUInfo)(nil),                 // 8: expanse.node.v1.CPUInfo
	(*MemoryInfo)(nil),              // 9: expanse.node.v1.MemoryInfo
	(*DiskInfo)(nil),                // 10: expanse.node.v1.DiskInfo
	(*NICInfo)(nil),                 // 11: expanse.node.v1.NICInfo
	(*GPUInfo)(nil),                 // 12: expanse.node.v1.GPUInfo
	(*TPMInfo)(nil),                 // 13: expanse.node.v1.TPMInfo
	(*ListResourcesRequest)(nil),    // 14: expanse.node.v1.ListResourcesRequest
	(*Resource)(nil),                // 15: expanse.node.v1.Resource
	(*ListResourcesResponse)(nil),   // 16: expanse.node.v1.ListResourcesResponse
	(*GetResourceRequest)(nil),      // 17: expanse.node.v1.GetResourceRequest
	(*ApplyResourcesRequest)(nil),   // 18: expanse.node.v1.ApplyResourcesRequest
	(*ApplyResourcesResponse)(nil),  // 19: expanse.node.v1.ApplyResourcesResponse
	(*DeleteResourceRequest)(nil),   // 20: expanse.node.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),  // 21: expanse.node.v1.DeleteResourceResponse
	(*ReconcileRequest)(nil),        // 22: expanse.node.v1.ReconcileRequest
	(*ReconcileEvent)(nil),          // 23: expanse.node.v1.ReconcileEvent
	(*StreamEventsRequest)(nil),     // 24: expanse.node.v1.StreamEventsRequest
	(*Event)(nil),                   // 25: expanse.node.v1.Event
	(*GetHealthRequest)(nil),        // 26: expanse.node.v1.GetHealthRequest
	(*HealthReport)(nil),            // 27: expanse.node.v1.HealthReport
	(*CheckResult)(nil),             // 28: expanse.node.v1.CheckResult
	(*ShutdownRequest)(nil),         // 29: expanse.node.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 30: expanse.node.v1.ShutdownResponse
	nil,                             // 31: expanse.node.v1.CheckResult.DetailsEntry
}
var file_proto_node_proto_depIdxs = []int32{
	1,  // 0: expanse.node.v1.NodeStatus.status:type_name -> expanse.node.v1.NodeStatus.Status
	7,  // 1: expanse.node.v1.Inventory.os:type_name -> expanse.node.v1.OSInfo
	8,  // 2: expanse.node.v1.Inventory.cpu:type_name -> expanse.node.v1.CPUInfo
	9,  // 3: expanse.node.v1.Inventory.memory:type_name -> expanse.node.v1.MemoryInfo
	10, // 4: expanse.node.v1.Inventory.disks:type_name -> expanse.node.v1.DiskInfo
	11, // 5: expanse.node.v1.Inventory.nics:type_name -> expanse.node.v1.NICInfo
	12, // 6: expanse.node.v1.Inventory.gpus:type_name -> expanse.node.v1.GPUInfo
	13, // 7: expanse.node.v1.Inventory.tpm:type_name -> expanse.node.v1.TPMInfo
	0,  // 8: expanse.node.v1.Resource.health:type_name -> expanse.node.v1.Health
	15, // 9: expanse.node.v1.ListResourcesResponse.resources:type_name -> expanse.node.v1.Resource
	28, // 10: expanse.node.v1.HealthReport.checks:type_name -> expanse.node.v1.CheckResult
	2,  // 11: expanse.node.v1.HealthReport.overall:type_name -> expanse.node.v1.HealthReport.OverallStatus
	0,  // 12: expanse.node.v1.CheckResult.status:type_name -> expanse.node.v1.Health
	31, // 13: expanse.node.v1.CheckResult.details:type_name -> expanse.node.v1.CheckResult.DetailsEntry
	3,  // 14: expanse.node.v1.NodeService.GetStatus:input_type -> expanse.node.v1.GetStatusRequest
	5,  // 15: expanse.node.v1.NodeService.GetInventory:input_type -> expanse.node.v1.GetInventoryRequest
	14, // 16: expanse.node.v1.NodeService.ListResources:input_type -> expanse.node.v1.ListResourcesRequest
	17, // 17: expanse.node.v1.NodeService.GetResource:input_type -> expanse.node.v1.GetResourceRequest
	18, // 18: expanse.node.v1.NodeService.ApplyResources:input_type -> expanse.node.v1.ApplyResourcesRequest
	20, // 19: expanse.node.v1.NodeService.DeleteResource:input_type -> expanse.node.v1.DeleteResourceRequest
	22, // 20: expanse.node.v1.NodeService.Reconcile:input_type -> expanse.node.v1.ReconcileRequest
	24, // 21: expanse.node.v1.NodeService.StreamEvents:input_type -> expanse.node.v1.StreamEventsRequest
	26, // 22: expanse.node.v1.NodeService.GetHealth:input_type -> expanse.node.v1.GetHealthRequest
	29, // 23: expanse.node.v1.NodeService.Shutdown:input_type -> expanse.node.v1.ShutdownRequest
	4,  // 24: expanse.node.v1.NodeService.GetStatus:output_type -> expanse.node.v1.NodeStatus
	6,  // 25: expanse.node.v1.NodeService.GetInventory:output_type -> expanse.node.v1.Inventory
	16, // 26: expanse.node.v1.NodeService.ListResources:output_type -> expanse.node.v1.ListResourcesResponse
	15, // 27: expanse.node.v1.NodeService.GetResource:output_type -> expanse.node.v1.Resource
	19, // 28: expanse.node.v1.NodeService.ApplyResources:output_type -> expanse.node.v1.ApplyResourcesResponse
	21, // 29: expanse.node.v1.NodeService.DeleteResource:output_type -> expanse.node.v1.DeleteResourceResponse
	23, // 30: expanse.node.v1.NodeService.Reconcile:output_type -> expanse.node.v1.ReconcileEvent
	25, // 31: expanse.node.v1.NodeService.StreamEvents:output_type -> expanse.node.v1.Event
	27, // 32: expanse.node.v1.NodeService.GetHealth:output_type -> expanse.node.v1.HealthReport
	30, // 33: expanse.node.v1.NodeService.Shutdown:output_type -> expanse.node.v1.ShutdownResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		EnumInfos:         file_proto_node_proto_enumTypes,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
