// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/replication.proto

// Wire messages for the exvol replication transport (Phase 06 T05).
// These carry the §4.3 replication protocol (T04's simulator types) over
// TCP connections between volume replicas on the exp0 mesh. Versioning /
// rolling-upgrade negotiation is a later-phase concern — frames carry a
// version byte; no negotiation yet.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteRequest is one replicated write sent from a primary to a
// secondary (§4.3 step 5). CRC is crc32c(Data), computed once at the
// primary and verified by the secondary (step 6a).
type WriteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	VolId  string                 `protobuf:"bytes,1,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	Seq    uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Offset uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Crc32C uint32                 `protobuf:"varint,5,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	// flush is a durability marker (§4.4: a device flush must fsync all
	// quorum replicas before returning). It consumes a sequence number
	// (keeping R2's gapless property) but carries no data.
	Flush         bool `protobuf:"varint,6,opt,name=flush,proto3" json:"flush,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetVolId() string {
	if x != nil {
		return x.VolId
	}
	return ""
}

func (x *WriteRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WriteRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequest) GetCrc32C() uint32 {
	if x != nil {
		return x.Crc32C
	}
	return 0
}

func (x *WriteRequest) GetFlush() bool {
	if x != nil {
		return x.Flush
	}
	return false
}

// WriteReply is the secondary's response (§4.3 step 6e / T04 Reply).
type WriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Gap           bool                   `protobuf:"varint,4,opt,name=gap,proto3" json:"gap,omitempty"`
	Retransmit    bool                   `protobuf:"varint,5,opt,name=retransmit,proto3" json:"retransmit,omitempty"`
	Resync        bool                   `protobuf:"varint,6,opt,name=resync,proto3" json:"resync,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReply) Reset() {
	*x = WriteReply{}
	mi := &file_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReply) ProtoMessage() {}

func (x *WriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReply.ProtoReflect.Descriptor instead.
func (*WriteReply) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WriteReply) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *WriteReply) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WriteReply) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *WriteReply) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *WriteReply) GetRetransmit() bool {
	if x != nil {
		return x.Retransmit
	}
	return false
}

func (x *WriteReply) GetResync() bool {
	if x != nil {
		return x.Resync
	}
	return false
}

func (x *WriteReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SeqInfo is one replica's durable-op record, reported at failover
// recovery (§4.3 step 4a): the seq and the CRC it was applied under.
// Recovery compares CRCs across replicas — the same seq with different
// CRCs is a divergent branch (§9): refuse automatic recovery.
type SeqInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Crc32C        uint32                 `protobuf:"varint,2,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeqInfo) Reset() {
	*x = SeqInfo{}
	mi := &file_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeqInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqInfo) ProtoMessage() {}

func (x *SeqInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqInfo.ProtoReflect.Descriptor instead.
func (*SeqInfo) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{2}
}

func (x *SeqInfo) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SeqInfo) GetCrc32C() uint32 {
	if x != nil {
		return x.Crc32C
	}
	return 0
}

// SeqQuery asks a replica for its last contiguous seq plus the per-seq
// CRC records (recovery step 4a).
type SeqQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolId         string                 `protobuf:"bytes,1,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeqQuery) Reset() {
	*x = SeqQuery{}
	mi := &file_proto_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeqQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqQuery) ProtoMessage() {}

func (x *SeqQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqQuery.ProtoReflect.Descriptor instead.
func (*SeqQuery) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{3}
}

func (x *SeqQuery) GetVolId() string {
	if x != nil {
		return x.VolId
	}
	return ""
}

type SeqQueryReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	VolId   string                 `protobuf:"bytes,1,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	LastSeq uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Ops     []*SeqInfo             `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	// Live primary health (§4.6), populated only when the answering node
	// currently holds the PRIMARY role for vol_id — a raft-independent
	// probe: the CLI's `volume inspect` dials this directly (same channel
	// as recovery's own probes) so a volume's live Degraded/ReadOnly
	// state stays observable even when the cluster's raft control plane
	// has itself lost write quorum and cannot persist a status update
	// (see runtime.querySeq / cmd_volume_ops.go's liveState).
	IsPrimary       bool  `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Replication     int32 `protobuf:"varint,5,opt,name=replication,proto3" json:"replication,omitempty"`
	HealthyReplicas int32 `protobuf:"varint,6,opt,name=healthy_replicas,json=healthyReplicas,proto3" json:"healthy_replicas,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SeqQueryReply) Reset() {
	*x = SeqQueryReply{}
	mi := &file_proto_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeqQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqQueryReply) ProtoMessage() {}

func (x *SeqQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqQueryReply.ProtoReflect.Descriptor instead.
func (*SeqQueryReply) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{4}
}

func (x *SeqQueryReply) GetVolId() string {
	if x != nil {
		return x.VolId
	}
	return ""
}

func (x *SeqQueryReply) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SeqQueryReply) GetOps() []*SeqInfo {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *SeqQueryReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *SeqQueryReply) GetReplication() int32 {
	if x != nil {
		return x.Replication
	}
	return 0
}

func (x *SeqQueryReply) GetHealthyReplicas() int32 {
	if x != nil {
		return x.HealthyReplicas
	}
	return 0
}

// FetchOpsRequest pulls ops (from_seq, to_seq] from a replica — the
// recovery step 4b/4c data movement. The replica re-reads the bytes
// from its own durable copy.
type FetchOpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolId         string                 `protobuf:"bytes,1,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	ToSeq         uint64                 `protobuf:"varint,3,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOpsRequest) Reset() {
	*x = FetchOpsRequest{}
	mi := &file_proto_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOpsRequest) ProtoMessage() {}

func (x *FetchOpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOpsRequest.ProtoReflect.Descriptor instead.
func (*FetchOpsRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{5}
}

func (x *FetchOpsRequest) GetVolId() string {
	if x != nil {
		return x.VolId
	}
	return ""
}

func (x *FetchOpsRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *FetchOpsRequest) GetToSeq() uint64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

type FetchOpsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*WriteRequest        `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOpsReply) Reset() {
	*x = FetchOpsReply{}
	mi := &file_proto_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOpsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOpsReply) ProtoMessage() {}

func (x *FetchOpsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOpsReply.ProtoReflect.Descriptor instead.
func (*FetchOpsReply) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{6}
}

func (x *FetchOpsReply) GetOps() []*WriteRequest {
	if x != nil {
		return x.Ops
	}
	return nil
}

// SnapListReply lists a replica's local snapshot names (T12 resync:
// common-ancestor discovery).
type SnapListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapListReply) Reset() {
	*x = SnapListReply{}
	mi := &file_proto_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapListReply) ProtoMessage() {}

func (x *SnapListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapListReply.ProtoReflect.Descriptor instead.
func (*SnapListReply) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{7}
}

func (x *SnapListReply) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// AdoptSeqRequest tells a replica its durable state now corresponds to
// seq after a resync (T12: the replica resumes inclusion in quorum at
// that seq). Full=true means the replica was rebuilt wholesale and its
// per-seq op records were reset with the image.
type AdoptSeqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolId         string                 `protobuf:"bytes,1,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Full          bool                   `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptSeqRequest) Reset() {
	*x = AdoptSeqRequest{}
	mi := &file_proto_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptSeqRequest) ProtoMessage() {}

func (x *AdoptSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptSeqRequest.ProtoReflect.Descriptor instead.
func (*AdoptSeqRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{8}
}

func (x *AdoptSeqRequest) GetVolId() string {
	if x != nil {
		return x.VolId
	}
	return ""
}

func (x *AdoptSeqRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AdoptSeqRequest) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

var File_proto_replication_proto protoreflect.FileDescriptor

const file_proto_replication_proto_rawDesc = "" +
	"\n" +
	"\x17proto/replication.proto\x12\x16expanse.replication.v1\"\x91\x01\n" +
	"\fWriteRequest\x12\x15\n" +
	"\x06vol_id\x18\x01 \x01(\tR\x05volId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06crc32c\x18\x05 \x01(\rR\x06crc32c\x12\x14\n" +
	"\x05flush\x18\x06 \x01(\bR\x05flush\"\xad\x01\n" +
	"\n" +
	"WriteReply\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x04R\alastSeq\x12\x10\n" +
	"\x03gap\x18\x04 \x01(\bR\x03gap\x12\x1e\n" +
	"\n" +
	"retransmit\x18\x05 \x01(\bR\n" +
	"retransmit\x12\x16\n" +
	"\x06resync\x18\x06 \x01(\bR\x06resync\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"3\n" +
	"\aSeqInfo\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06crc32c\x18\x02 \x01(\rR\x06crc32c\"!\n" +
	"\bSeqQuery\x12\x15\n" +
	"\x06vol_id\x18\x01 \x01(\tR\x05volId\"\xe0\x01\n" +
	"\rSeqQueryReply\x12\x15\n" +
	"\x06vol_id\x18\x01 \x01(\tR\x05volId\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x121\n" +
	"\x03ops\x18\x03 \x03(\v2\x1f.expanse.replication.v1.SeqInfoR\x03ops\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12 \n" +
	"\vreplication\x18\x05 \x01(\x05R\vreplication\x12)\n" +
	"\x10healthy_replicas\x18\x06 \x01(\x05R\x0fhealthyReplicas\"Z\n" +
	"\x0fFetchOpsRequest\x12\x15\n" +
	"\x06vol_id\x18\x01 \x01(\tR\x05volId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x15\n" +
	"\x06to_seq\x18\x03 \x01(\x04R\x05toSeq\"G\n" +
	"\rFetchOpsReply\x126\n" +
	"\x03ops\x18\x01 \x03(\v2$.expanse.replication.v1.WriteRequestR\x03ops\"%\n" +
	"\rSnapListReply\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"N\n" +
	"\x0fAdoptSeqRequest\x12\x15\n" +
	"\x06vol_id\x18\x01 \x01(\tR\x05volId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04full\x18\x03 \x01(\bR\x04fullB\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_replication_proto_rawDescOnce sync.Once
	file_proto_replication_proto_rawDescData []byte
)

func file_proto_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)))
	})
	return file_proto_replication_proto_rawDescData
}

var file_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_replication_proto_goTypes = []any{
	(*WriteRequest)(nil),    // 0: expanse.replication.v1.WriteRequest
	(*WriteReply)(nil),      // 1: expanse.replication.v1.WriteReply
	(*SeqInfo)(nil),         // 2: expanse.replication.v1.SeqInfo
	(*SeqQuery)(nil),        // 3: expanse.replication.v1.SeqQuery
	(*SeqQueryReply)(nil),   // 4: expanse.replication.v1.SeqQueryReply
	(*FetchOpsRequest)(nil), // 5: expanse.replication.v1.FetchOpsRequest
	(*FetchOpsReply)(nil),   // 6: expanse.replication.v1.FetchOpsReply
	(*SnapListReply)(nil),   // 7: expanse.replication.v1.SnapListReply
	(*AdoptSeqRequest)(nil), // 8: expanse.replication.v1.AdoptSeqRequest
}
var file_proto_replication_proto_depIdxs = []int32{
	2, // 0: expanse.replication.v1.SeqQueryReply.ops:type_name -> expanse.replication.v1.SeqInfo
	0, // 1: expanse.replication.v1.FetchOpsReply.ops:type_name -> expanse.replication.v1.WriteRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_replication_proto_init() }
func file_proto_replication_proto_init() {
	if File_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_proto_depIdxs,
		MessageInfos:      file_proto_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_proto = out.File
	file_proto_replication_proto_goTypes = nil
	file_proto_replication_proto_depIdxs = nil
}
