// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/replication.proto

// Wire messages for the exvol replication transport (Phase 06 T05).
// These carry the §4.3 replication protocol (T04's simulator types) over
// TCP connections between volume replicas on the exp0 mesh. Versioning /
// rolling-upgrade negotiation is a later-phase concern — frames carry a
// version byte; no negotiation yet.

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteRequest is one replicated write sent from a primary to a
// secondary (§4.3 step 5). CRC is crc32c(Data), computed once at the
// primary and verified by the secondary (step 6a).
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolId         string                 `protobuf:"bytes,1,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Crc32C        uint32                 `protobuf:"varint,5,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetVolId() string {
	if x != nil {
		return x.VolId
	}
	return ""
}

func (x *WriteRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WriteRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequest) GetCrc32C() uint32 {
	if x != nil {
		return x.Crc32C
	}
	return 0
}

// WriteReply is the secondary's response (§4.3 step 6e / T04 Reply).
type WriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Gap           bool                   `protobuf:"varint,4,opt,name=gap,proto3" json:"gap,omitempty"`
	Retransmit    bool                   `protobuf:"varint,5,opt,name=retransmit,proto3" json:"retransmit,omitempty"`
	Resync        bool                   `protobuf:"varint,6,opt,name=resync,proto3" json:"resync,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReply) Reset() {
	*x = WriteReply{}
	mi := &file_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReply) ProtoMessage() {}

func (x *WriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReply.ProtoReflect.Descriptor instead.
func (*WriteReply) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WriteReply) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *WriteReply) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WriteReply) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *WriteReply) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *WriteReply) GetRetransmit() bool {
	if x != nil {
		return x.Retransmit
	}
	return false
}

func (x *WriteReply) GetResync() bool {
	if x != nil {
		return x.Resync
	}
	return false
}

func (x *WriteReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_replication_proto protoreflect.FileDescriptor

const file_proto_replication_proto_rawDesc = "" +
	"\n" +
	"\x17proto/replication.proto\x12\x16expanse.replication.v1\"{\n" +
	"\fWriteRequest\x12\x15\n" +
	"\x06vol_id\x18\x01 \x01(\tR\x05volId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x16\n" +
	"\x06crc32c\x18\x05 \x01(\rR\x06crc32c\"\xad\x01\n" +
	"\n" +
	"WriteReply\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\x04R\alastSeq\x12\x10\n" +
	"\x03gap\x18\x04 \x01(\bR\x03gap\x12\x1e\n" +
	"\n" +
	"retransmit\x18\x05 \x01(\bR\n" +
	"retransmit\x12\x16\n" +
	"\x06resync\x18\x06 \x01(\bR\x06resync\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reasonB\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_replication_proto_rawDescOnce sync.Once
	file_proto_replication_proto_rawDescData []byte
)

func file_proto_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)))
	})
	return file_proto_replication_proto_rawDescData
}

var (
	file_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_proto_replication_proto_goTypes  = []any{
		(*WriteRequest)(nil), // 0: expanse.replication.v1.WriteRequest
		(*WriteReply)(nil),   // 1: expanse.replication.v1.WriteReply
	}
)

var file_proto_replication_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_replication_proto_init() }
func file_proto_replication_proto_init() {
	if File_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_proto_depIdxs,
		MessageInfos:      file_proto_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_proto = out.File
	file_proto_replication_proto_goTypes = nil
	file_proto_replication_proto_depIdxs = nil
}
