// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VolumeState is a volume's lifecycle state (§4.1).
type VolumeState int32

const (
	VolumeState_VOLUME_STATE_UNSPECIFIED VolumeState = 0
	VolumeState_VOLUME_STATE_CREATING    VolumeState = 1
	VolumeState_VOLUME_STATE_HEALTHY     VolumeState = 2
	VolumeState_VOLUME_STATE_DEGRADED    VolumeState = 3
	VolumeState_VOLUME_STATE_READONLY    VolumeState = 4
	VolumeState_VOLUME_STATE_RESYNCING   VolumeState = 5
	VolumeState_VOLUME_STATE_FAILED      VolumeState = 6
	VolumeState_VOLUME_STATE_DELETING    VolumeState = 7
	// Split-brain divergence detected (§9): same seq, different CRC on
	// two replicas. Automatic recovery refused; an operator must choose
	// (`expanse ctl volume diverged`). All copies are preserved.
	VolumeState_VOLUME_STATE_NEEDS_MANUAL_RECOVERY VolumeState = 8
)

// Enum value maps for VolumeState.
var (
	VolumeState_name = map[int32]string{
		0: "VOLUME_STATE_UNSPECIFIED",
		1: "VOLUME_STATE_CREATING",
		2: "VOLUME_STATE_HEALTHY",
		3: "VOLUME_STATE_DEGRADED",
		4: "VOLUME_STATE_READONLY",
		5: "VOLUME_STATE_RESYNCING",
		6: "VOLUME_STATE_FAILED",
		7: "VOLUME_STATE_DELETING",
		8: "VOLUME_STATE_NEEDS_MANUAL_RECOVERY",
	}
	VolumeState_value = map[string]int32{
		"VOLUME_STATE_UNSPECIFIED":           0,
		"VOLUME_STATE_CREATING":              1,
		"VOLUME_STATE_HEALTHY":               2,
		"VOLUME_STATE_DEGRADED":              3,
		"VOLUME_STATE_READONLY":              4,
		"VOLUME_STATE_RESYNCING":             5,
		"VOLUME_STATE_FAILED":                6,
		"VOLUME_STATE_DELETING":              7,
		"VOLUME_STATE_NEEDS_MANUAL_RECOVERY": 8,
	}
)

func (x VolumeState) Enum() *VolumeState {
	p := new(VolumeState)
	*p = x
	return p
}

func (x VolumeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumeState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_storage_proto_enumTypes[0].Descriptor()
}

func (VolumeState) Type() protoreflect.EnumType {
	return &file_proto_storage_proto_enumTypes[0]
}

func (x VolumeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumeState.Descriptor instead.
func (VolumeState) EnumDescriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

// ReplicaRole is one replica's position in the replication protocol (§4.3).
type ReplicaRole int32

const (
	ReplicaRole_REPLICA_ROLE_UNSPECIFIED ReplicaRole = 0
	ReplicaRole_REPLICA_ROLE_PRIMARY     ReplicaRole = 1
	ReplicaRole_REPLICA_ROLE_SECONDARY   ReplicaRole = 2
	ReplicaRole_REPLICA_ROLE_RESYNCING   ReplicaRole = 3
	ReplicaRole_REPLICA_ROLE_STALE       ReplicaRole = 4
)

// Enum value maps for ReplicaRole.
var (
	ReplicaRole_name = map[int32]string{
		0: "REPLICA_ROLE_UNSPECIFIED",
		1: "REPLICA_ROLE_PRIMARY",
		2: "REPLICA_ROLE_SECONDARY",
		3: "REPLICA_ROLE_RESYNCING",
		4: "REPLICA_ROLE_STALE",
	}
	ReplicaRole_value = map[string]int32{
		"REPLICA_ROLE_UNSPECIFIED": 0,
		"REPLICA_ROLE_PRIMARY":     1,
		"REPLICA_ROLE_SECONDARY":   2,
		"REPLICA_ROLE_RESYNCING":   3,
		"REPLICA_ROLE_STALE":       4,
	}
)

func (x ReplicaRole) Enum() *ReplicaRole {
	p := new(ReplicaRole)
	*p = x
	return p
}

func (x ReplicaRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicaRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_storage_proto_enumTypes[1].Descriptor()
}

func (ReplicaRole) Type() protoreflect.EnumType {
	return &file_proto_storage_proto_enumTypes[1]
}

func (x ReplicaRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicaRole.Descriptor instead.
func (ReplicaRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{1}
}

// VolumeSpec is the immutable-except-size volume configuration written
// once by the controller.
type VolumeSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "vol-" + 16 hex.
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SizeBytes uint64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Storage class name: "default", "fast", "local", "ceph" (§4.2).
	Class string `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	// 1..5.
	Replication   int32 `protobuf:"varint,6,opt,name=replication,proto3" json:"replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeSpec) Reset() {
	*x = VolumeSpec{}
	mi := &file_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeSpec) ProtoMessage() {}

func (x *VolumeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeSpec.ProtoReflect.Descriptor instead.
func (*VolumeSpec) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VolumeSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *VolumeSpec) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VolumeSpec) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *VolumeSpec) GetReplication() int32 {
	if x != nil {
		return x.Replication
	}
	return 0
}

// Replica is one placement's live state (§4.1).
type Replica struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role   ReplicaRole            `protobuf:"varint,2,opt,name=role,proto3,enum=expanse.storage.v1.ReplicaRole" json:"role,omitempty"`
	// e.g. "rpool/volumes/vol-1a2b".
	ZvolPath string `protobuf:"bytes,3,opt,name=zvol_path,json=zvolPath,proto3" json:"zvol_path,omitempty"`
	// Last durable sequence on this replica (§4.3).
	Sequence uint64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Last time this replica responded, UnixNano.
	LastSeenUnixNano int64 `protobuf:"varint,5,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	Healthy          bool  `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Replica) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Replica) GetRole() ReplicaRole {
	if x != nil {
		return x.Role
	}
	return ReplicaRole_REPLICA_ROLE_UNSPECIFIED
}

func (x *Replica) GetZvolPath() string {
	if x != nil {
		return x.ZvolPath
	}
	return ""
}

func (x *Replica) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Replica) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

func (x *Replica) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// VolumeStatus is the mutable volume state, updated CAS-style by the
// controller and replicas.
type VolumeStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bumped on every membership change (§4.1).
	Generation uint64      `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	State      VolumeState `protobuf:"varint,2,opt,name=state,proto3,enum=expanse.storage.v1.VolumeState" json:"state,omitempty"`
	// Node ID holding the primary lease.
	Primary string `protobuf:"bytes,3,opt,name=primary,proto3" json:"primary,omitempty"`
	// Last acked write sequence.
	Sequence      uint64     `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Placement     []*Replica `protobuf:"bytes,5,rep,name=placement,proto3" json:"placement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatus) Reset() {
	*x = VolumeStatus{}
	mi := &file_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatus) ProtoMessage() {}

func (x *VolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatus.ProtoReflect.Descriptor instead.
func (*VolumeStatus) Descriptor() ([]byte, []int) {
	return file_proto_storage_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeStatus) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *VolumeStatus) GetState() VolumeState {
	if x != nil {
		return x.State
	}
	return VolumeState_VOLUME_STATE_UNSPECIFIED
}

func (x *VolumeStatus) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *VolumeStatus) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *VolumeStatus) GetPlacement() []*Replica {
	if x != nil {
		return x.Placement
	}
	return nil
}

var File_proto_storage_proto protoreflect.FileDescriptor

const file_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x13proto/storage.proto\x12\x12expanse.storage.v1\"\xa5\x01\n" +
	"\n" +
	"VolumeSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x14\n" +
	"\x05class\x18\x05 \x01(\tR\x05class\x12 \n" +
	"\vreplication\x18\x06 \x01(\x05R\vreplication\"\xd9\x01\n" +
	"\aReplica\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x123\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1f.expanse.storage.v1.ReplicaRoleR\x04role\x12\x1b\n" +
	"\tzvol_path\x18\x03 \x01(\tR\bzvolPath\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12-\n" +
	"\x13last_seen_unix_nano\x18\x05 \x01(\x03R\x10lastSeenUnixNano\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\"\xd6\x01\n" +
	"\fVolumeStatus\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.expanse.storage.v1.VolumeStateR\x05state\x12\x18\n" +
	"\aprimary\x18\x03 \x01(\tR\aprimary\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x129\n" +
	"\tplacement\x18\x05 \x03(\v2\x1b.expanse.storage.v1.ReplicaR\tplacement*\x8e\x02\n" +
	"\vVolumeState\x12\x1c\n" +
	"\x18VOLUME_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15VOLUME_STATE_CREATING\x10\x01\x12\x18\n" +
	"\x14VOLUME_STATE_HEALTHY\x10\x02\x12\x19\n" +
	"\x15VOLUME_STATE_DEGRADED\x10\x03\x12\x19\n" +
	"\x15VOLUME_STATE_READONLY\x10\x04\x12\x1a\n" +
	"\x16VOLUME_STATE_RESYNCING\x10\x05\x12\x17\n" +
	"\x13VOLUME_STATE_FAILED\x10\x06\x12\x19\n" +
	"\x15VOLUME_STATE_DELETING\x10\a\x12&\n" +
	"\"VOLUME_STATE_NEEDS_MANUAL_RECOVERY\x10\b*\x95\x01\n" +
	"\vReplicaRole\x12\x1c\n" +
	"\x18REPLICA_ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REPLICA_ROLE_PRIMARY\x10\x01\x12\x1a\n" +
	"\x16REPLICA_ROLE_SECONDARY\x10\x02\x12\x1a\n" +
	"\x16REPLICA_ROLE_RESYNCING\x10\x03\x12\x16\n" +
	"\x12REPLICA_ROLE_STALE\x10\x04B\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_storage_proto_rawDescOnce sync.Once
	file_proto_storage_proto_rawDescData []byte
)

func file_proto_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)))
	})
	return file_proto_storage_proto_rawDescData
}

var file_proto_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_storage_proto_goTypes = []any{
	(VolumeState)(0),     // 0: expanse.storage.v1.VolumeState
	(ReplicaRole)(0),     // 1: expanse.storage.v1.ReplicaRole
	(*VolumeSpec)(nil),   // 2: expanse.storage.v1.VolumeSpec
	(*Replica)(nil),      // 3: expanse.storage.v1.Replica
	(*VolumeStatus)(nil), // 4: expanse.storage.v1.VolumeStatus
}
var file_proto_storage_proto_depIdxs = []int32{
	1, // 0: expanse.storage.v1.Replica.role:type_name -> expanse.storage.v1.ReplicaRole
	0, // 1: expanse.storage.v1.VolumeStatus.state:type_name -> expanse.storage.v1.VolumeState
	3, // 2: expanse.storage.v1.VolumeStatus.placement:type_name -> expanse.storage.v1.Replica
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_storage_proto_init() }
func file_proto_storage_proto_init() {
	if File_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_proto_rawDesc), len(file_proto_storage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_proto_depIdxs,
		EnumInfos:         file_proto_storage_proto_enumTypes,
		MessageInfos:      file_proto_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_proto = out.File
	file_proto_storage_proto_goTypes = nil
	file_proto_storage_proto_depIdxs = nil
}
