// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/store.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	CommandType_COMMAND_TYPE_PUT         CommandType = 1
	CommandType_COMMAND_TYPE_DELETE      CommandType = 2
	CommandType_COMMAND_TYPE_TXN         CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_PUT",
		2: "COMMAND_TYPE_DELETE",
		3: "COMMAND_TYPE_TXN",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED": 0,
		"COMMAND_TYPE_PUT":         1,
		"COMMAND_TYPE_DELETE":      2,
		"COMMAND_TYPE_TXN":         3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_store_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_store_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{0}
}

type OpKind int32

const (
	OpKind_OP_KIND_UNSPECIFIED OpKind = 0
	OpKind_OP_KIND_PUT         OpKind = 1
	OpKind_OP_KIND_DELETE      OpKind = 2
	OpKind_OP_KIND_CHECK       OpKind = 3
)

// Enum value maps for OpKind.
var (
	OpKind_name = map[int32]string{
		0: "OP_KIND_UNSPECIFIED",
		1: "OP_KIND_PUT",
		2: "OP_KIND_DELETE",
		3: "OP_KIND_CHECK",
	}
	OpKind_value = map[string]int32{
		"OP_KIND_UNSPECIFIED": 0,
		"OP_KIND_PUT":         1,
		"OP_KIND_DELETE":      2,
		"OP_KIND_CHECK":       3,
	}
)

func (x OpKind) Enum() *OpKind {
	p := new(OpKind)
	*p = x
	return p
}

func (x OpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_store_proto_enumTypes[1].Descriptor()
}

func (OpKind) Type() protoreflect.EnumType {
	return &file_proto_store_proto_enumTypes[1]
}

func (x OpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpKind.Descriptor instead.
func (OpKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{1}
}

// Command is the unit of replication: every store mutation is encoded as a
// Command, proposed through Raft, and applied deterministically by the FSM
// on every node (see internal/store/raftstore/fsm.go). The encoding is
// versioned from day one so Phase 16's rolling upgrade can distinguish old
// and new formats.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoding version. Currently 1. A node that sees a version it does not
	// understand must refuse to apply the entry (fail loudly, never guess).
	Version uint32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type    CommandType `protobuf:"varint,2,opt,name=type,proto3,enum=expanse.store.v1.CommandType" json:"type,omitempty"`
	// For PUT and DELETE: the target key and value.
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// CAS precondition: 0 means "must not exist" for PUT-style CAS; for
	// DELETE, 0 means unconditional.
	Expect uint64 `protobuf:"varint,5,opt,name=expect,proto3" json:"expect,omitempty"`
	// For TXN: the ordered list of operations.
	Ops []*Op `protobuf:"bytes,6,rep,name=ops,proto3" json:"ops,omitempty"`
	// Set by the leader before proposing. The FSM NEVER uses time.Now() —
	// determinism requires timestamps to travel inside the command.
	TimestampUnixNs int64 `protobuf:"varint,7,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	// Client-supplied idempotency key. A retried write (network failure after
	// commit) reuses the same RequestID and the FSM deduplicates it.
	RequestId     string `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Command) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

func (x *Command) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *Command) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          OpKind                 `protobuf:"varint,1,opt,name=kind,proto3,enum=expanse.store.v1.OpKind" json:"kind,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expect        uint64                 `protobuf:"varint,4,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_proto_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_proto_store_proto_rawDescGZIP(), []int{1}
}

func (x *Op) GetKind() OpKind {
	if x != nil {
		return x.Kind
	}
	return OpKind_OP_KIND_UNSPECIFIED
}

func (x *Op) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Op) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Op) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

var File_proto_store_proto protoreflect.FileDescriptor

const file_proto_store_proto_rawDesc = "" +
	"\n" +
	"\x11proto/store.proto\x12\x10expanse.store.v1\"\x89\x02\n" +
	"\aCommand\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.expanse.store.v1.CommandTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x16\n" +
	"\x06expect\x18\x05 \x01(\x04R\x06expect\x12&\n" +
	"\x03ops\x18\x06 \x03(\v2\x14.expanse.store.v1.OpR\x03ops\x12*\n" +
	"\x11timestamp_unix_ns\x18\a \x01(\x03R\x0ftimestampUnixNs\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\"r\n" +
	"\x02Op\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.expanse.store.v1.OpKindR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x16\n" +
	"\x06expect\x18\x04 \x01(\x04R\x06expect*p\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMMAND_TYPE_PUT\x10\x01\x12\x17\n" +
	"\x13COMMAND_TYPE_DELETE\x10\x02\x12\x14\n" +
	"\x10COMMAND_TYPE_TXN\x10\x03*Y\n" +
	"\x06OpKind\x12\x17\n" +
	"\x13OP_KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOP_KIND_PUT\x10\x01\x12\x12\n" +
	"\x0eOP_KIND_DELETE\x10\x02\x12\x11\n" +
	"\rOP_KIND_CHECK\x10\x03B\"Z github.com/expanse/expanse/protob\x06proto3"

var (
	file_proto_store_proto_rawDescOnce sync.Once
	file_proto_store_proto_rawDescData []byte
)

func file_proto_store_proto_rawDescGZIP() []byte {
	file_proto_store_proto_rawDescOnce.Do(func() {
		file_proto_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_store_proto_rawDesc), len(file_proto_store_proto_rawDesc)))
	})
	return file_proto_store_proto_rawDescData
}

var file_proto_store_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_store_proto_goTypes = []any{
	(CommandType)(0), // 0: expanse.store.v1.CommandType
	(OpKind)(0),      // 1: expanse.store.v1.OpKind
	(*Command)(nil),  // 2: expanse.store.v1.Command
	(*Op)(nil),       // 3: expanse.store.v1.Op
}
var file_proto_store_proto_depIdxs = []int32{
	0, // 0: expanse.store.v1.Command.type:type_name -> expanse.store.v1.CommandType
	3, // 1: expanse.store.v1.Command.ops:type_name -> expanse.store.v1.Op
	1, // 2: expanse.store.v1.Op.kind:type_name -> expanse.store.v1.OpKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_store_proto_init() }
func file_proto_store_proto_init() {
	if File_proto_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_store_proto_rawDesc), len(file_proto_store_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_store_proto_goTypes,
		DependencyIndexes: file_proto_store_proto_depIdxs,
		EnumInfos:         file_proto_store_proto_enumTypes,
		MessageInfos:      file_proto_store_proto_msgTypes,
	}.Build()
	File_proto_store_proto = out.File
	file_proto_store_proto_goTypes = nil
	file_proto_store_proto_depIdxs = nil
}
