# Block runtime module for net/haproxy.
#
# Stateless: run several replicas with anti-affinity behind an EXPOSE_VIP
# port; expanse-block-run (haproxy.go) writes haproxy.cfg from spec.config.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     configFile  # haproxy.cfg generated by expanse-block-run
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, configFile, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (net/haproxy)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.haproxy}/bin/haproxy -db -f ${configFile}";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
