# Block runtime module for monitor/grafana.
#
# Run singleton with a storage volume for grafana.db. expanse-block-run
# provisions the "expanse-prometheus" datasource (spec.config.prometheusUrl)
# and the shipped dashboard, and configures Grafana through GF_* variables.
#
# Contract: import and call with:
#   {
#     pkgs           # nixpkgs
#     name           # instance name (systemd unit name)
#     port           # web UI port, from spec.config.port
#     provisioning   # provisioning dir generated by expanse-block-run
#     mountPath      # data volume mount point (spec.storage[0].mountPath)
#     user           # runtime user (default "expanse-block")
#   }
{ pkgs, name, port, provisioning, mountPath, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (monitor/grafana)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    environment = {
      GF_PATHS_DATA = mountPath;
      GF_PATHS_PROVISIONING = provisioning;
      GF_SERVER_HTTP_PORT = toString port;
      GF_ANALYTICS_REPORTING_ENABLED = "false";
      GF_ANALYTICS_CHECK_FOR_UPDATES = "false";
    };
    serviceConfig = {
      ExecStart = "${pkgs.grafana}/bin/grafana server --homepath=${pkgs.grafana}/share/grafana";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
