# Block runtime module for monitor/uptime-kuma.
#
# One uptime-kuma per instance, active/passive over the SINGLETON strategy like
# security/vaultwarden. Its SQLite database lives on the volume;
# expanse-block-run (uptimekuma.go) builds the environment and SQLite preload.
#
# Contract: import and call with:
#   {
#     pkgs        # nixpkgs
#     name        # instance name (systemd unit name)
#     environment # the environment generated by expanse-block-run
#     user        # runtime user (default "expanse-block")
#   }
{ pkgs, name, environment, user ? "expanse-block" }:
{
  systemd.services."expanse-block-${name}" = {
    description = "expanse block ${name} (monitor/uptime-kuma)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    inherit environment;
    serviceConfig = {
      ExecStart = "${pkgs.uptime-kuma}/bin/uptime-kuma-server";
      User = user;
      Restart = "always";
      RestartSec = "1s";
      NoNewPrivileges = true;
      ProtectHome = true;
      PrivateTmp = true;
    };
  };
}
